### DISCUSSION TITLE
ch_PP-OCRv4_rec_distill，报错

### DISCUSSION THREAD

**Discussion by dengmingD** [PaddlePaddle/PaddleOCR#12192] [Q&A]
配置文件如下：
<details>
```yaml
Global:
  debug: false
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 100
  print_batch_step: 100
  save_model_dir: ./output/recv4_icbc/
  save_epoch_step: 1
  eval_batch_step:
  - 0
  - 20000
  cal_metric_during_train: true
  pretrained_model: ./train_models/ch_PP-OCRv4_rec_server_train/best_accuracy
  checkpoints: 
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/gonghang_keys.txt
  max_text_length: &max_text_length 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.00001
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 3.0e-05
Architecture:
  model_type: rec
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained: 
      freeze_params: true
      return_all_feats: true
      model_type: rec
      algorithm: SVTR
      Transform: null
      Backbone:
        name: SVTRNet
        img_size:
        - 48
        - 320
        out_char_num: 40
        out_channels: 192
        patch_merging: Conv
        embed_dim:
        - 64
        - 128
        - 256
        depth:
        - 3
        - 6
        - 3
        num_heads:
        - 2
        - 4
        - 8
        mixer:
        - Conv
        - Conv
        - Conv
        - Conv
        - Conv
        - Conv
        - Global
        - Global
        - Global
        - Global
        - Global
        - Global
        local_mixer:
        - - 5
          - 5
        - - 5
          - 5
        - - 5
          - 5
        last_stage: false
        prenorm: true
      Head:
        name: MultiHead
        head_list:
          - CTCHead:
              Neck:
                name: svtr
                dims: 120
                depth: 2
                hidden_dims: 120
                kernel_size: [1, 3]
                use_guide: True
              Head:
                fc_decay: 0.00001
          - NRTRHead:
              nrtr_dim: 384
              max_text_length: *max_text_length
    Student:
      pretrained: 
      freeze_params: false
      return_all_feats: true
      model_type: rec
      algorithm: SVTR
      Transform: null
      Backbone:
        name: PPLCNetV3
        scale: 0.95
      Head:
        name: MultiHead
        head_list:
          - CTCHead:
              Neck:
                name: svtr
                dims: 120
                depth: 2
                hidden_dims: 120
                kernel_size: [1, 3]
                use_guide: True
              Head:
                fc_decay: 0.00001
          - NRTRHead:
              nrtr_dim: 384
              max_text_length: *max_text_length
Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDKDLoss:
      weight: 0.1
      model_name_pairs:
      - - Student
        - Teacher
      key: head_out
      multi_head: true
      alpha: 1.0
      beta: 2.0
      dis_head: gtc
      name: dkd
  - DistillationCTCLoss:
      weight: 1.0
      model_name_list:
      - Student
      key: head_out
      multi_head: true
  - DistillationNRTRLoss:
      weight: 1.0
      smoothing: false
      model_name_list:
      - Student
      key: head_out
      multi_head: true
  - DistillCTCLogits:
      weight: 1.0
      reduction: mean
      model_name_pairs:
      - - Student
        - Teacher
      key: head_out
PostProcess:
  name: DistillationCTCLabelDecode
  model_name:
  - Student
  key: head_out
  multi_head: true
Metric:
  name: DistillationMetric
  base_metric_name: RecMetric
  main_indicator: acc
  key: Student
  ignore_space: false
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /media/huilang01/新加卷/ocr/icbc_code/icbc_bank_train_data
    label_file_list:
    - /media/huilang01/新加卷/ocr/icbc_code/icbc_bank_train_data/labels_50w.txt
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecAug:
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: true
    num_workers: 8
    use_shared_memory: true
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /media/huilang01/新加卷/ocr/icbc_code/icbc_bank_test_data
    label_file_list:
    - /media/huilang01/新加卷/ocr/icbc_code/icbc_bank_test_data/labels.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 4
profiler_options: null
```
</details>

报错如下：
```bash
[2023/08/17 16:56:36] ppocr INFO: Initialize indexs of datasets:['/media/huilang01/新加卷/ocr/icbc_code/icbc_bank_train_data/labels_50w.txt']
list index out of range
[2023/08/17 16:56:37] ppocr INFO: Initialize indexs of datasets:['/media/huilang01/新加卷/ocr/icbc_code/icbc_bank_test_data/labels.txt']
Traceback (most recent call last):
  File "/home/huilang01/work/projects/ocr27/PaddleOCR27/tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "/home/huilang01/work/projects/ocr27/PaddleOCR27/tools/train.py", line 135, in main
    model = build_model(config['Architecture'])
  File "/home/huilang01/work/projects/ocr27/PaddleOCR27/ppocr/modeling/architectures/__init__.py", line 34, in build_model
    arch = getattr(mod, name)(config)
  File "/home/huilang01/work/projects/ocr27/PaddleOCR27/ppocr/modeling/architectures/distillation_model.py", line 47, in __init__
    model = BaseModel(model_config)
  File "/home/huilang01/work/projects/ocr27/PaddleOCR27/ppocr/modeling/architectures/base_model.py", line 76, in __init__
    self.head = build_head(config["Head"])
  File "/home/huilang01/work/projects/ocr27/PaddleOCR27/ppocr/modeling/heads/__init__.py", line 71, in build_head
    module_class = eval(module_name)(**config)
  File "/home/huilang01/work/projects/ocr27/PaddleOCR27/ppocr/modeling/heads/rec_multi_head.py", line 74, in __init__
    out_channels=out_channels_list['NRTRLabelDecode'])
KeyError: 'NRTRLabelDecode'
I0817 16:56:37.444166  3359 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-08-17 16:56:38,217 Pod failed
```

问题出在这行代码：
out_channels=out_channels_list['NRTRLabelDecode'])
因为字典里没有这个key所以报错，字典里只有key为‘CTCLabelDecode’的值。
