### DISCUSSION TITLE
PaddleOCR ch_PP-OCRv4_rec_hgnet 在读取数据时出现list index out of range，但是以前的版本并不会

### DISCUSSION THREAD

**Discussion by dhhcj** [PaddlePaddle/PaddleOCR#12239] [Q&A]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.
这个是V4版本：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26632100/db5ea615-7397-4d75-8e45-43d4869b5226)
旧的V2版本：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26632100/c4adf060-95bc-4e58-91b1-66ae3b01caab)
并不会出现这个问题

**Comment by dhhcj** [comment]
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/26632100/1715fada-a503-4fd0-9cac-28edc42aca96)
是在65行报的这个问题，我记得这两个map是db检测模型的呀

**Comment by walasad** [comment]
Same problem here, could you please share your .yml and train_data folder structure

**Comment by iweirman** [comment]
看样子是由于V4文字检测模型配置文件引入的一个问题。

应该是引入了[动态shrink ratio(dynamic shrink ratio):](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/PP-OCRv4_introduction.md)在训练中，shrink ratio由固定值调整为动态变化，随着训练epoch的增加，shrink ratio从0.4线性增加到0.6。该策略在PP-OCRv4学生检测模型上，hmean从76.97%提升到78.24%。

```yml
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
        total_epoch: *epoch_num
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
        total_epoch: *epoch_num
```

应该不会影响识别效果？ @dhhcj  大佬，你测试过这个模型效果了吗？
