### DISCUSSION TITLE
Inference with padding

### DISCUSSION THREAD

**Discussion by kwang19113** [PaddlePaddle/PaddleOCR#12286] [Q&A]
Hi I've trained a CPPD model with my custom dataset. In the training and validating configs i set padding to True. I just wanna ask if i use the infer_rec.py will it automatically add the padding? if not then how can i add padding to the image for better accuracy.

ConfigFile:
```
Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/LMDB_Val
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          ignore_index: *ignore_index
      - SVTRRecAug:
      - SVTRRecResizeImg:
          image_shape: [3, 32, 100]
          padding: true #true
      - KeepKeys:
          keep_keys: ['image', 'label', 'label_node', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./train_data/val_15_4_2024_lmdb
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          ignore_index: *ignore_index
      - SVTRRecResizeImg:
          image_shape: [3, 32, 100]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'label_node','length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 2

```
