### DISCUSSION TITLE
Export detection model to inference

### DISCUSSION THREAD

**Discussion by PerizatKurmanbaeva** [PaddlePaddle/PaddleOCR#12333] [Q&A]
HI, can you help to me? I  trained my own detection model.  When I test my model  with 
`python tools/infer_det.py -c config_detector.yaml -o Global.infer_img="./images/624.jpg" Global.pretrained_model="./detector_best_acc/best_accuracy" `, 
It work well. But when I export this model with 
`python tools/export_model.py -c ./config_detector.yaml -o  Global.pretrained_model="./detector_best_acc/best_accuracy" Global.save_inference_dir="./output/det_db_inference/"`
 and running
` python tools/infer/predict_det.py --det_algorithm="DB" --data_model_dir="./output/data_db_inference/" --image_dir="./images" --use_gpu=False. `
It doesn't work

**Comment by cuicheng01** [comment]
Hi, what does it look like that does not meet expectations?

**Comment by PerizatKurmanbaeva** [comment]
> Hi, what does it look like that does not meet expectations?

When I use it like pretrained model, it gives me image with detection box. But after exporting to inference gives None. I was testing on same images.

**Comment by PerizatKurmanbaeva** [comment]
> Hi, what does it look like that does not meet expectations?

this is Architecture in config.yaml
```
Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

```
