### DISCUSSION TITLE
db++用于弯曲文字检测训练时报错，有办法解决吗

### DISCUSSION THREAD

**Discussion by zjlw** [PaddlePaddle/PaddleOCR#12558] [Q&A]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：2.4.2  PaddleOCR：2.7 问题相关组件/Related components：
- 运行指令/Command Code：python tools/train.py -c configs/det/det_r50_db++_icdar15.yml
- 完整报错/Complete Error Message：
```text
Traceback (most recent call last):
  File "tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 198, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/PaddleOCR/tools/program.py", line 394, in train
    cur_metric = eval(
  File "/home/PaddleOCR/tools/program.py", line 572, in eval
    post_result = post_process_class(preds, batch_numpy[1])
  File "/home/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 241, in __call__
    boxes, scores = self.polygons_from_bitmap(pred[batch_index],
  File "/home/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 84, in polygons_from_bitmap
    box = self.unclip(points, self.unclip_ratio)
  File "/home/PaddleOCR/ppocr/postprocess/db_postprocess.py", line 160, in unclip
    expanded = np.array(offset.Execute(distance))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

我发现配置文件和训练文件代码对不上，box的类型，配置文件是det_box_type,训练代码是box_type,所以我修改了配置文件，让他和训练代码保持一致，并设置为poly。
```yaml
det_r50_db++_idcdar15.yml
Global:
  debug: false
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/det_r50_icdar15/
  save_epoch_step: 200
  eval_batch_step:
  - 0
  - 100
  cal_metric_during_train: false
  pretrained_model: /home/PaddleOCR/pretrain_models/ResNet50_dcn_asf_synthtext_pretrained/det_r50_db++_icdar15_train/best_accuracy
  # pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: /home/PaddleOCR/dataset/seal/test/circle_Aug00518.png
  save_res_path: ./checkpoints/det_db/predicts_db.txt
Architecture:
  model_type: det
  algorithm: DB++
  Transform: null
  Backbone:
    name: ResNet
    layers: 50
    dcn_stage: [False, True, True, True]
  Neck:
    name: DBFPN
    out_channels: 256
    use_asf: True
  Head:
    name: DBHead
    k: 50
Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: BCELoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: DecayLearningRate
    learning_rate: 0.007
    epochs: 1000
    factor: 0.9
    end_lr: 0
  weight_decay: 0.0001
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
  box_type: 'poly' # 'quad' or 'poly'
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/PaddleOCR/dataset/seal                                                                      
    label_file_list:                                                                                            
    - /home/PaddleOCR/dataset/seal/800train.txt                                                  
    ratio_list:                                                                                                 
    - 1.0 
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 10
        keep_ratio: true
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 4
    num_workers: 0
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/PaddleOCR/dataset/seal                                                                        
    label_file_list:                                                                                            
    - /home/PaddleOCR/dataset/seal/80test.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest:
        image_shape:
        - 1152
        - 2048
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.48109378172549
        - 0.45752457890196
        - 0.40787054090196
        std:
        - 1.0
        - 1.0
        - 1.0
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 0
profiler_options: null
```

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We provide AceIssueSolver to solve issues, do you want it? (Please write yes/no):

请尽量不要包含图片在问题中/Please try to not include the image in the issue.
