### DISCUSSION TITLE
图片行数太多，识别的时候会漏识别其中几行文字，是什么原因导致？

### DISCUSSION THREAD

**Discussion by chongqingwei** [PaddlePaddle/PaddleOCR#12573] [Q&A]
/请
/提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：linux
- 版本号/Version：Paddle：  PaddleOCR：2.6  问题相关组件/Related components： 
- 运行指令/Command Code：无
- 完整报错/Complete Error Message：无

我们提供了AceIssueSolver来帮助你解答问题，你是否想要它来解答(请填写yes/no)?/We [provide]([url](url)) AceIssueSolver to solve issues, do you want it? (Please write yes/no):
/ yes 

请尽量不要包含图片在问题中/Please try to not include the image in the [issue.]([url](
/))

**Comment by chongqingwei** [comment]
[](url)
![test2](https://github.com/PaddlePaddle/PaddleOCR/assets/20459797/4d03f22b-66aa-4d47-a062-880bbdf4ebb0)

**Comment by chongqingwei** [comment]
上面这个图片中，有几行识别不出来？用最新的PP-OCRv4

**Comment by chongqingwei** [comment]
def read_params():
    cfg = Config()

    #params for text detector
    cfg.det_algorithm = "DB"
    cfg.det_model_dir = "./inference/ch_PP-OCRv4_det_server_infer/"
    cfg.det_limit_side_len = 2000 #960
    cfg.det_limit_type = 'max'

    #DB parmas
    cfg.det_db_thresh = 0.1 #0.3
    cfg.det_db_box_thresh = 0.1 #0.5            # 0.3
    cfg.det_db_unclip_ratio = 1.2            # 1.6
    cfg.use_dilation = False
    cfg.det_db_score_mode = "fast"

    #EAST parmas
    cfg.det_east_score_thresh = 0.6 #0.8        # 0.6
    cfg.det_east_cover_thresh = 0.1
    cfg.det_east_nms_thresh = 0.2

    #params for text recognizer
    cfg.rec_algorithm = "CRNN"
    cfg.rec_model_dir = "./inference/ch_PP-OCRv4_rec_server_infer/"

    cfg.rec_image_shape = "3, 32, 320"          # "3, 48, 320"
    cfg.rec_batch_num = 6
    cfg.max_text_length = 35 #25

    cfg.rec_char_dict_path = "./ppocr/utils/ppocr_keys_v1.txt"
    cfg.use_space_char = True

    #params for text classifier
    cfg.use_angle_cls = False                   # False
    cfg.cls_model_dir = "./inference/ch_ppocr_mobile_v2.0_cls_infer/"
    cfg.cls_image_shape = "3, 48, 192"
    cfg.label_list = ['0', '180']
    cfg.cls_batch_num = 30
    cfg.cls_thresh = 0.9

    cfg.use_pdserving = False
    cfg.use_tensorrt = False
    # cfg.drop_score = 0.5

    return cfg

**Comment by data-ant** [comment]
大概率是检测的问题

**Comment by chongqingwei** [comment]
> 大概率是检测的问题

您好，怎么解决？看着图片很清晰。

**Comment by SWHL** [comment]
如果问题仍然存在，建议用可视化文本检测结果，估计是漏检了。

**Comment by jdx** [comment]
Thanks for bringing this up Kyle - this is a real pain point, especially when working with multiple instances of the same provider type.

I've been thinking through a few approaches (AI-assisted analysis):

## Current State

fnox already supports `StringOrSecretRef` for provider config fields, allowing things like:
```toml
[providers.vault-one]
type = "vault"
address = "https://my-vault-one.com/"
token = { secret = "VAULT_ONE_TOKEN" }  # references another secret
```

But this doesn't solve the bootstrap problem - how do you *obtain* the token in the first place?

## Proposed Path Forward

I'm leaning toward a **hybrid approach**:

### Phase 1: Generic `credential-command`

```toml
[providers.vault-one]
type = "vault"
address = "https://my-vault-one.com/"
path = "secret/over/here"
credential-command = ["vault", "login", "-method=oidc", "-field=token"]
```

- Array format avoids shell parsing/injection issues
- Command stdout becomes the credential
- fnox sets provider-specific env vars before running (e.g., `VAULT_ADDR`)
- Similar pattern to SSH `ProxyCommand` or Git credential helpers
- Works for any provider immediately

### Phase 2: Provider-specific credential configs

```toml
[providers.vault-one]
type = "vault"
address = "https://my-vault-one.com/"
credential = { method = "oidc", role = "my-role" }
```

- Type-safe, better error messages
- Provider implements auth natively (no shelling out)
- Add common auth methods over time (OIDC, AppRole, etc.)

## Open Questions

1. Should credentials be cached for the session duration?
2. For `credential-command`, do we need template variables like `{address}`, or is setting env vars sufficient?
3. Should this be consistent across all providers, or is it okay for some providers to have richer credential options than others?

Thoughts?

---

*This response was drafted with AI assistance*
