### DISCUSSION TITLE
请问哪里可以下载到LMDB格式的Union14M-L数据集

### DISCUSSION THREAD

**Discussion by CharmingHue** [PaddlePaddle/PaddleOCR#12688] [Q&A]
最近在调试CPPD识别算法过程中，想重新训练，看到配置文件中有Union14M-LMDB-L训练数据，找了一圈没找到，请问到哪里可以下载到LMDB格式的Union14M-L数据集？
```
Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./Union14M-LMDB-L
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          ignore_index: *ignore_index
      - SVTRRecResizeImg:
          image_shape: [3, 32, 128]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'label_node', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8
```
