### DISCUSSION TITLE
cppd算法使用报错 ValueError: Sample larger than population or is negative

### DISCUSSION THREAD

**Discussion by csuer411** [PaddlePaddle/PaddleOCR#12889] [Q&A]
- 系统环境/System Environment：linux
- 版本号/Version：Paddle：2.5.0  PaddleOCR：2.7.0.3 
- 问题相关组件/Related components：使用当前的github的dygraph分支中的cppd算法，结合自定义数据集训练时报错
- 运行指令/Command Code：python3 tools/train.py -c  rec_svtrnet_cppd_base_stn_ch.yml
- 完整报错/Complete Error Message：
[2023/10/14 15:28:14] ppocr ERROR: When parsing line train/num/4186.jpg	929070
, error happened with msg: Traceback (most recent call last):
  File "/home/aistudio/Paddleocr/ppocr/data/simple_dataset.py", line 159, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/Paddleocr/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/aistudio/Paddleocr/ppocr/data/imaug/label_ops.py", line 1625, in __call__
    text, text_node_index, text_node_num = self.encodech(text)
  File "/home/aistudio/Paddleocr/ppocr/data/imaug/label_ops.py", line 1724, in encodech
    none_char_index = sample(character_index,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
[2023/10/14 15:28:14] ppocr ERROR: When parsing line train/num/4426.jpg	222011
, error happened with msg: Traceback (most recent call last):
  File "/home/aistudio/Paddleocr/ppocr/data/simple_dataset.py", line 159, in __getitem__
    outs = transform(data, self.ops)
  File "/home/aistudio/Paddleocr/ppocr/data/imaug/__init__.py", line 56, in transform
    data = op(data)
  File "/home/aistudio/Paddleocr/ppocr/data/imaug/label_ops.py", line 1625, in __call__
    text, text_node_index, text_node_num = self.encodech(text)
  File "/home/aistudio/Paddleocr/ppocr/data/imaug/label_ops.py", line 1724, in encodech
    none_char_index = sample(character_index,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

上面的报错信息都是一样的，就不全贴上来了。
配置文件如下：
```
Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./handocr
  save_epoch_step: 10
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: /home/aistudio/rec_svtr_cppd_base_stn_ch_train/best_model.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: /home/aistudio/num_dict.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./handocr/rec/predicts_svtr_cppd_base_ch_stn.txt


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.e-8
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed char_node_embed pos_node_embed char_pos_embed vis_pos_embed
  one_dim_param_no_weight_decay: True
  lr:
    name: Cosine
    learning_rate: 0.000125 # 4gpus 128bs
    warmup_epoch: 5

Architecture:
  model_type: rec
  algorithm: CPPD
  Transform:
    name: STN_ON
    tps_inputsize: [32, 64]
    tps_outputsize: [32, 256]
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size: [32, 256]
    patch_merging: 'Conv'
    embed_dim: [128, 256, 384]
    depth: [6, 6, 4]
    num_heads: [4, 8, 12]
    mixer: ['Conv','Conv','Conv','Conv','Conv','Conv', 'Conv','Conv', 'Global','Global','Global','Global','Global','Global','Global','Global','Global','Global']
    local_mixer: [[5, 5], [5, 5], [5, 5]]
    last_stage: False
    prenorm: True
  Head:
    name: CPPDHead
    dim: 384
    vis_seq: 128
    ch: &ch True

Loss:
  name: CPPDLoss
  ignore_index: &ignore_index 7000 # must be greater than the number of character classes
  smoothing: True
  sideloss_weight: 1.0

PostProcess:
  name: CPPDLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio
    label_file_list:
      - /home/aistudio/train/train_num.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          ignore_index: *ignore_index
          ch: *ch
      - SVTRRecResizeImg:
          image_shape: [3, 64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'label_node', 'label_index', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/eval
    label_file_list:
      - /home/aistudio/eval/eval.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CPPDLabelEncode: # Class handling label
          ignore_index: *ignore_index
          ch: *ch
      - SVTRRecResizeImg:
          image_shape: [3, 64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'label_node','label_index','length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 2
```
我看dygraph分支中是支持cppd的，请问具体问题是什么呢
