### DISCUSSION TITLE
Why evaluation score always 0.0

### DISCUSSION THREAD

**Discussion by minhhoang2705** [PaddlePaddle/PaddleOCR#12919] [Q&A]
I have been training CRNN for Vietnamese text recognition for days but my evaluation score always 0.0 in spite of my training score improve 
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/86783160/3bd04caa-752e-4b0f-bd08-65a35dcd8b70)
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/86783160/e3b70b7c-912f-4fe0-81a9-038e1d4b02f4)

Here is my CRNN config file. If there anything wrong please let me know.
```
Global:
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/r34_vd_none_bilstm_ctc_vie_v2/
  save_epoch_step: 5
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/rec_r34_vd_none_bilstm_ctc_v2.0_train/best_accuracy
  checkpoints: ./output/rec/r34_vd_none_bilstm_ctc_vie_v2/latest
  save_inference_dir:
  use_visualdl: False
  infer_img: null
  # for data or label process
  character_dict_path: ./ppocr/utils/dict/custom.txt
  max_text_length: 1000
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_r34_vd_none_bilstm_ctc.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/2nd_phase/rec_data/double_word_data
    label_file_list: ./train_data/2nd_phase/rec_data/train_data.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 1024]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/2nd_phase/rec_data/Vietnamese
    label_file_list: ./train_data/2nd_phase/rec_data/output.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 1024]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 6
```
