### DISCUSSION TITLE
在 PaddleOCR 中添加新样本后模型性能显着下降

### DISCUSSION THREAD

**Discussion by OleksandrZhytnyk** [PaddlePaddle/PaddleOCR#13540] [Q&A]
问题描述
你好，PaddleOCR社区，

我遇到了一个关于我的OCR模型的重大问题，希望能从社区中获得一些见解和帮助。

背景
今年四月，我使用PaddleOCR训练了一个OCR模型，并取得了令人满意的性能指标，Hmean为0.82。模型在验证集上的表现非常好。

数据集由使用英文的PDF文档图片组成，使用[PPOCRLabel](https://github.com/Mushroomcat9998/PaddleOCR/blob/main/PPOCRLabel/README.md)进行标注。

使用的模型配置文件是[ch_PP-OCRv4_det_teacher.yml](https://github.com/PaddlePaddle/PaddleOCR/blob/main/configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_teacher.yml)。

问题
最近，我在训练数据集中添加了800个新样本，以进一步改进模型。然而，在添加这些新样本并使用相同的config.yaml文件重新训练模型后，我观察到一个奇怪的现象。最初，模型的性能指标从Hmean的0.7在几个epoch后急剧下降到0.1（如果我使用较低的学习率，指标下降得较慢）。我也在四月份的版本数据集上进行了测试，遇到了同样的问题。

为解决问题所采取的步骤
更新PaddleOCR库到最新版本。
检查标签的正确性。
使用默认的配置文件。
观察结果
添加新样本后，模型的性能显著下降。
性能下降非常突然，并在前几个epoch内发生。
两次训练都使用了相同的config.yaml文件。
这是我使用的配置文件

```yaml
Global:
debug: false
use_gpu: true
epoch_num: &epoch_num 500
log_smooth_window: 20
print_batch_step: 10
save_model_dir: ./output/det_PP-OCRv4
save_epoch_step: 500000
eval_batch_step:

0
83
cal_metric_during_train: false
checkpoints: null
pretrained_model: ./ch_PP-OCRv4_det_server_train/best_accuracy.pdparams
save_inference_dir: null
use_visualdl: false
infer_img: doc/imgs_en/img_10.jpg
save_res_path: ./checkpoints/det_db/predicts_db.txt
distributed: true
Architecture:
model_type: det
algorithm: DB
Transform: null
Backbone:
name: PPHGNet_small
det: True
Neck:
name: LKPAN
out_channels: 256
intracl: true
Head:
name: PFHeadLocal
k: 50
mode: "large"

Loss:
name: DBLoss
balance_loss: true
main_loss_type: DiceLoss
alpha: 5
beta: 10
ohem_ratio: 3

Optimizer:
name: RMSProp
beta1: 0.9
beta2: 0.999
lr:
name: Cosine
learning_rate: 0.0001 #(8*8c)
warmup_epoch: 2
regularizer:
name: L2
factor: 1e-6

PostProcess:
name: DBPostProcess
thresh: 0.4
box_thresh: 0.7
max_candidates: 4000
unclip_ratio: 2

Metric:
name: DetMetric
main_indicator: hmean

Train:
dataset:
name: SimpleDataSet
data_dir: ./det/dataset_det
label_file_list:
- ./det/dataset_det/train.txt
ratio_list: [1.0]
transforms:
- DecodeImage:
img_mode: BGR
channel_first: false
- DetLabelEncode: null
- CopyPaste: null
- IaaAugment:
augmenter_args:
- type: Fliplr
args:
p: 0.5
- type: Affine
args:
rotate:
- -10
- 10
- type: Resize
args:
size:
- 0.5
- 3
- EastRandomCropData:
size:
- 640
- 640
max_tries: 50
keep_ratio: true
- MakeBorderMap:
shrink_ratio: 0.4
thresh_min: 0.3
thresh_max: 0.7
total_epoch: *epoch_num
- MakeShrinkMap:
shrink_ratio: 0.4
min_text_size: 8
total_epoch: *epoch_num
- NormalizeImage:
scale: 1./255.
mean:
- 0.485
- 0.456
- 0.406
std:
- 0.229
- 0.224
- 0.225
order: hwc
- ToCHWImage: null
- KeepKeys:
keep_keys:
- image
- threshold_map
- threshold_mask
- shrink_map
- shrink_mask
loader:
shuffle: true
drop_last: false
batch_size_per_card: 12
num_workers: 12

Eval:
dataset:
name: SimpleDataSet
data_dir: ./det/dataset_det/
label_file_list:
- ./det/dataset_det/test.txt
transforms:
- DecodeImage:
img_mode: BGR
channel_first: false
- DetLabelEncode: null
- DetResizeForTest: null
- NormalizeImage:
scale: 1./255.
mean:
- 0.485
- 0.456
- 0.406
std:
- 0.229
- 0.224
- 0.225
order: hwc
- ToCHWImage: null
- KeepKeys:
keep_keys:
- image
- shape
- polys
- ignore_tags
loader:
shuffle: false
drop_last: false
batch_size_per_card: 1
num_workers: 12
profiler_options: null
```

![image](https://github.com/user-attachments/assets/28452c36-e1b1-4aac-8d2b-74f3984f07d3)

我将不胜感激任何可以解释这种行为的帮助或建议。如果您需要进一步澄清我的案例，请随时提问。
