### DISCUSSION TITLE
超大的表格识别问题

### DISCUSSION THREAD

**Discussion by lwinhong** [PaddlePaddle/PaddleOCR#13619] [Q&A]
## 问题：
我的项目使用表格都是很大的，ppstructure完全识别不出来或者效果极差
![image](https://github.com/user-attachments/assets/968ca432-3cfd-4999-9e87-b1ebfc20090f)
![image](https://github.com/user-attachments/assets/bc38c576-1730-42b0-a4f0-ec3d5678cb1a)

## 我使用的解决方案：
我用了TableGenertation模拟生成了100张大表格进行了1000轮的训练，最后acc只有0.458
![image](https://github.com/user-attachments/assets/5dd45a23-7878-43de-9a05-f1472734b242)
预测和导出的模型识别结果和训练之前几乎没有改变

``` yml
Global:
  use_gpu: True
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/SLANet_ch
  save_epoch_step: 400
  # evaluation is run every 331 iterations after the 0th iteration
  eval_batch_step: [0, 331]
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/ch_ppstructure_mobile_v2.0_SLANet_train_my/best_accuracy.pdparams
  #pretrained_model: ./pretrain_models/ch_ppstructure_mobile_v2.0_SLANet_train/best_accuracy.pdparams
  checkpoints:
  save_inference_dir: ./output/SLANet_ch/infer
  use_visualdl: False
  infer_img: ./train_data/table/img/border_1_4ZT8GPERH8KKP6CUR9IN.jpg
  # for data or label process
  character_dict_path: ppocr/utils/dict/table_structure_dict_ch.txt
  character_type: en
  max_text_length: &max_text_length 1000
  box_format: &box_format xyxyxyxy # 'xywh', 'xyxy', 'xyxyxyxy'
  infer_mode: False
  use_sync_bn: True
  save_res_path: output/infer

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  lr:
    learning_rate: 0.00017
  regularizer:
    name: 'L2'
    factor: 0.00000

Architecture:
  model_type: table
  algorithm: SLANet
  Backbone:
    name: PPLCNet
    scale: 1.0
    pretrained: True
    use_ssld: True
  Neck:
    name: CSPPAN
    out_channels: 96
  Head:
    name: SLAHead
    hidden_size: 256
    max_text_length: *max_text_length
    loc_reg_num: &loc_reg_num 8

Loss:
  name: SLALoss
  structure_weight: 1.0
  loc_weight: 2.0
  loc_loss: smooth_l1

PostProcess:
  name: TableLabelDecode
  merge_no_span_structure: &merge_no_span_structure True

Metric:
  name: TableMetric
  main_indicator: acc
  compute_bbox_metric: False
  loc_reg_num: *loc_reg_num
  box_format: *box_format
  del_thead_tbody: True

Train:
  dataset:
    name: PubTabDataSet
    data_dir: train_data/table/
    label_file_list: [train_data/table/train.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bboxes', 'bbox_masks', 'length', 'shape']
  loader:
    shuffle: True
    batch_size_per_card: 16
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: PubTabDataSet
    data_dir: train_data/table/
    label_file_list: [train_data/table/val.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bboxes', 'bbox_masks', 'length', 'shape']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 3
    num_workers: 1

```

## 疑问
各位大佬，有没有什么好的解决方案？请不吝赐教

@GreatV

**Comment by GreatV** [comment]
增加训练配置文件中的图片尺寸估计会有用，现在是488，对于大尺寸的表格图片会缩放。

**Reply by lwinhong** [reply]
> 增加训练配置文件中的图片尺寸估计会有用，现在是488，对于大尺寸的表格图片会缩放。

我的图片宽度最大有6000px， 我应该改多大？

应该改哪个，配置文件中有六个488的的配置项。 
Train 和 Eval 各有三个

``` yml
Train:
  dataset:
      transforms:
        - ResizeTableImage:
            max_len: 488
        - PaddingTableImage:
            size: [488, 488]

....
```
