### DISCUSSION TITLE
使用ch_PP-OCRv3_det_student.yml微调文字检测模型总是有漏检情况如何解决

### DISCUSSION THREAD

**Discussion by gokamisama** [PaddlePaddle/PaddleOCR#14339] [Q&A]
我的微调数据有800张（650train+150eval）最终的acc有98+：
![图片](https://github.com/user-attachments/assets/0ef70e95-14e2-4283-81c3-86ffef964812)
但是总是发现一个问题：
![图片](https://github.com/user-attachments/assets/380b02af-7380-4f92-95c4-e8811c716e0a)
图片中有些行挨着很近的两列（数量和单价）只能检测到一列，我尝试调低过det_db_thresh和det_db_box_thresh，都没有什么效果。

我尝试分析过原因，可能是**因为两列挨着太近了，要让模型区分成两列学习难度较大**导致的。

请问我如何才能解决这个问题呢？请各位大佬能不吝赐教

**Comment by GreatV** [comment]
根据你的问题描述和提供的信息，微调文字检测模型出现漏检的情况可能是由以下几个原因导致的。以下是一些可能的解决办法：

---

### 原因分析及解决方案

#### 1. **数据标注和样本问题**
   - **问题分析**：
     - 你的训练集和验证集数量为 650 + 150 张，数据量相对较小。如果训练数据中类似「挨得很近的两列文字」的样本不足，模型可能无法很好地学习这种分割模式。
     - 数据标注质量也可能影响模型的表现，尤其是相邻文字区域过于密集，标注框可能不够精确或区分度不高。

   - **解决办法**：
     1. **增加数据样本量**：扩充训练数据，特别是包含「挨得很近的两列文字」的样本，确保模型能够学习到这些特殊场景。
     2. **增强数据多样性**：
        - 使用数据增强（例如不同的旋转角度、缩放比例）来覆盖更多的检测场景。
        - 结合 `CopyPaste` 增强（配置文件中已经启用），手动创建一些「两列紧靠」的样本。
     3. **检查标注文件**：
        - 确保标注框的质量高，尤其是对于「紧挨的两列文字」，标注框应尽可能精确地分隔两列。

---

#### 2. **模型后处理参数调整**
   - **问题分析**：
     - 你提到已经尝试调整 `det_db_thresh` 和 `det_db_box_thresh`（分别为二值化阈值和框过滤阈值），但效果不明显。这可能说明模型检测到的特征图本身表现不足，或者后处理参数仍需要更细致的调整。

   - **解决办法**：
     1. **调整参数范围**：
        - `det_db_box_thresh`：建议尝试更大范围的调整，降低到 0.3～0.5，确保不会因为过滤阈值过高而漏掉较小的框。
        - `det_db_unclip_ratio`：增加此参数的值（如从默认的 1.5 提升到 2.0 或更高），扩大检测框的解包边界，避免一些紧密的文字区域被合并为一个框。
     2. **开启或关闭膨胀操作**：
        - 如果检测框过小，可以尝试在推理阶段开启膨胀操作（`use_dilation: True`），以扩大感兴趣区域。

---

#### 3. **模型结构及训练策略**
   - **问题分析**：
     - 微调模型使用的 `ch_PP-OCRv3_det_student.yml` 是轻量级学生模型，如果目标场景较复杂（如相邻文字间距小），这种模型可能存在不足。
     - 训练过程中可能需要更长时间或更好的初始化（预训练权重）来提高表现。

   - **解决办法**：
     1. **尝试使用更强的预训练模型**：
        - 在配置文件 `Global.pretrained_model` 中，可以尝试使用 `teacher` 模型（如 `ch_PP-OCRv3_det_teacher.yml` 的权重），然后进行蒸馏训练。
        - 蒸馏训练能够通过 `teacher` 模型提供更丰富的监督信号，提升学生模型的检测效果。
     2. **增加训练轮次或优化学习率**：
        - 当前配置中 `epoch_num` 为 200，可以尝试增加到 300～500，并对学习率进行调整。
        - 若训练后期效果提升缓慢，可以降低学习率（如从 `0.0001` 降到 `0.00001`）。
     3. **尝试调整 `MakeShrinkMap` 和 `MakeBorderMap` 参数**：
        - `shrink_ratio`：适当缩小此参数（如从 `0.4` 调整为 `0.3`），以便更好地分离紧挨的文字。
        - `min_text_size`：确保设置合理（如 `8`），避免过小的文字区域被忽略。

---

#### 4. **模型评估和调试**
   - **问题分析**：
     - 当前模型的 `acc` 达到 98%，但实际检测效果仍有漏检，说明单纯依靠 `acc` 作为评估指标不足以反映模型在细粒度场景下的表现。

   - **解决办法**：
     1. **通过可视化分析问题**：
        - 使用 PaddleOCR 的预测脚本（如 `tools/infer_det.py`）对验证集或测试集进行预测，并可视化输出框，分析具体漏检区域是否存在特征相似或框重叠的问题。
     2. **调整评价指标**：
        - 关注 `hmean`（F1 值）和 `recall`，这一指标能更好地反映模型的实际检测能力。
     3. **逐步调试模型**：
        - 在调试过程中，可以仅对部分样本进行训练和评估，快速验证配置调整的效果。

---

### 示例调整（针对配置文件 `ch_PP-OCRv3_det_student.yml`）
以下是一些具体的调整建议：

```yaml
PostProcess:
  name: DBPostProcess
  thresh: 0.3  # 可尝试降低至 0.2 或更低
  box_thresh: 0.5  # 调低以避免漏掉小框
  max_candidates: 1000
  unclip_ratio: 2.0  # 增大此参数，扩大文字框

Train:
  dataset:
    transforms:
      - MakeBorderMap:
          shrink_ratio: 0.3  # 缩小收缩比例
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.3
          min_text_size: 8  # 确保小文字也能被检测

Optimizer:
  lr:
    learning_rate: 0.00005  # 调低学习率，适合微调任务
```

---

### 参考讨论
1. [ch_PP-OCRv3_det_student.yml文本检测微调hmean一直为0](https://github.com/PaddlePaddle/PaddleOCR/discussions/14250)
   - 提及了微调训练数据尺寸和模型调整的相关经验。
   
2. [ch_v4 det训练后，完全检测不出来](https://github.com/PaddlePaddle/PaddleOCR/discussions/14197)
   - 对于数据量较小的场景推荐使用预训练模型以及适当调整超参数。

---

### 总结
- **数据**：扩充训练集并增加紧靠列的样本，增强数据多样性。
- **后处理**：调整 `box_thresh` 和 `unclip_ratio` 等参数。
- **模型结构**：尝试使用蒸馏训练或更强的 `teacher` 模型。
- **调试与分析**：通过可视化预测结果和调试指标，定位具体问题并优化。

以上方法可以结合实际问题逐步尝试，最终找到最适合你场景的优化方案。

---
*Response generated by 🤖 [feifei-bot](https://github.com/GreatV/feifei) | chatgpt-4o-latest*
