### DISCUSSION TITLE
在AiStudio车牌识别微调教程中，使用ch_PP-OCRv4-det进行文本检测微调训练时，hmeans一直很低，是学习率太低的问题吗？

### DISCUSSION THREAD

**Discussion by Boom-Wang** [PaddlePaddle/PaddleOCR#14354] [Q&A]
在AiStudio车牌识别微调教程中，使用ch_PP-OCRv4-det进行文本检测微调训练时，hmeans一直很低。
当epoch=120时，hmean依旧只有18%，且best_epoch=26，收敛速度很慢

除了模型我更换未PP-OCRv4之外，教程中的其他代码内容基本不变，为何教程中车牌识别的文本检测在微调后hmean能达到99%，而我这一直只有18%，是要调整学习率吗？

![微信截图_20241209093958](https://github.com/user-attachments/assets/ae948a8b-a815-4faa-8f81-26b22dd2ec4b)
![微信截图_20241209094019](https://github.com/user-attachments/assets/c610da7d-59c1-46dc-b478-da16c46e0842)

**Comment by GreatV** [comment]
在微调 **ch_PP-OCRv4-det** 的过程中，`hmean` 指标始终较低（如仅为 18%），可以从以下几个方面排查问题并优化训练流程：

---

### 1. **学习率问题**
- **现状**：你的学习率设置为 `0.0001`，并使用 `Cosine` 学习率衰减。
- **优化建议**：
  - 对于小数据集（如 200 张图像），学习率通常需要更低以确保模型更好地拟合数据。如 `1e-5` 或 `5e-5`。
  - 如果训练效果差，可以尝试固定学习率（`Const`），或者提高 `warmup_epoch` 的值（如设为 5），使模型前期收敛更稳定。
  - 若模型出现过拟合现象，可适当降低学习率，并尝试正则化策略（如增大 `L2 regularizer.factor`）。

---

### 2. **数据集特性问题**
- **现状**：你的训练数据集仅有 200 张图片，且尺寸为 `350x48`。
- **优化建议**：
  1. **数据增强**：
     - 你的配置中已使用了 `IaaAugment` 和 `EastRandomCropData`，但可能仍不足以覆盖场景多样性。尝试增加更多数据增强方法（如 `RandomRotate`, `ColorJitter` 等）。
     - 确保增强后的图片保留了目标区域的完整性。
  2. **图片尺寸**：
     - 图片尺寸较小（`350x48`），可能导致检测精度下降。可以适当调整 `resize size` 参数（如 `640x640`），确保模型可以捕获更多细节。
  3. **数据量不足**：
     - 200 张数据可能不足以支撑稳定的训练。建议增加数据量，或者使用预训练模型（`ch_PP-OCRv4-det`）进行微调。
     - 如果条件有限，可以采用数据增强或合成数据的方法扩充训练集。

---

### 3. **模型配置问题**
- **现状**：
  - 你使用了 `DB`（Differentiable Binarization）算法，且预训练模型为 `ch_PP-OCRv4-det`。
- **优化建议**：
  1. **预训练模型的选择**：
     - 确保使用的 `ch_PP-OCRv4-det` 预训练模型适合你的场景。如果你的场景与通用场景差异较大，可以尝试使用更贴近场景的预训练模型。
  2. **Teacher 模型蒸馏**：
     - 若数据量不足且模型效果较差，可以尝试蒸馏训练（`Teacher-Student`）。如在配置中引入 `ch_PP-OCRv4-det` 的 Teacher 模型，提升 Student 模型的表现。
     - 示例配置（加入 Teacher 模型）：
       ```yaml
       Global:
         pretrained_model: path_to_teacher_model.pdparams
       Architecture:
         name: Distillation
         StudentModel:
           model_type: det
           algorithm: DB
         TeacherModel:
           model_type: det
           algorithm: DB
       Loss:
         DistillationLoss:
           losses:
           - name: L2Loss
       ```
  3. **模型头部参数（DBHead）**：
     - 调整 `DBHead.k` 参数的值（如从 `50` 改为 `100`），以适应场景中目标文本尺寸的特性。

---

### 4. **训练配置问题**
- **现状**：
  - 当前设置的 `epoch_num=200`，`batch_size_per_card=4`。
- **优化建议**：
  1. **训练轮次**：
     - 小数据集下 200 个 epoch 可能过多，建议减少到 50-100 个 epoch，并在验证集上观察效果。
  2. **批量大小**：
     - 小数据集下，`batch_size_per_card=4` 通常较小，导致训练不稳定。可增大至 `8` 或 `16`，以提高训练稳定性。
  3. **验证频率**：
     - 当前 `eval_batch_step=[0, 50]`，建议调整为 `[0, 20]`，以更频繁地监控模型性能。

---

### 5. **PostProcess 和评估问题**
- **现状**：
  - `DBPostProcess` 的 `thresh=0.3`，`box_thresh=0.6`。
- **优化建议**：
  - 调整 `thresh` 和 `box_thresh` 的值（如分别改为 `0.2` 和 `0.5`），以提升检测框的召回率。
  - 适当减小 `unclip_ratio`（如从 `1.5` 改为 `1.3`）以优化检测框的精度。

---

### 6. **分析损失曲线**
- **现状**：`best_epoch=26`，说明模型在 26 个 epoch 后开始过拟合。
- **优化建议**：
  - 检查训练日志中的损失曲线（`loss`, `lr`），确认是否存在以下问题：
    1. **梯度爆炸或消失**：降低初始学习率或加大正则化。
    2. **训练不足**：增大学习率或调整优化器。
  - 启用 `VisualDL`（设置 `Global.use_visualdl=true`），可视化损失和评估指标。

---

### 7. **参考类似问题**
根据 [相关讨论](https://github.com/PaddlePaddle/PaddleOCR/discussions/14197) 和 [文档](https://github.com/PaddlePaddle/PaddleOCR/discussions/14250)，可能存在以下场景特异性问题：
- **数据标注错误**：检查数据集标注（如 `polys` 和 `ignore_tags`）是否正确。
- **文本尺寸要求**：确保文本尺寸符合 `min_text_size=8` 的要求。

---

### 总结
根据上述分析，可以尝试以下调整：
1. **学习率**：降低至 `1e-5` 或 `5e-5`，并使用 `Const` 学习率。
2. **数据增强**：增加更多增强方法（`ColorJitter`，`RandomRotate`）。
3. **PostProcess**：调整 `thresh` 为 `0.2`，`box_thresh` 为 `0.5`。
4. **训练配置**：减少 `epoch_num`，增大 `batch_size_per_card`。
5. **蒸馏训练**：引入 Teacher 模型进行蒸馏。

通过以上优化，`hmean` 指标应能显著提升。

---
*Response generated by 🤖 [feifei-bot](https://github.com/GreatV/feifei) | chatgpt-4o-latest*
