### DISCUSSION TITLE
No Images in train dataset, please ensure

### DISCUSSION THREAD

**Discussion by bound123** [PaddlePaddle/PaddleOCR#14393] [Q&A]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

```bash
Traceback (most recent call last):
  File "D:\PaddleOCR-main\tools\train.py", line 269, in <module>
    main(config, device, logger, vdl_writer, seed)
  File "D:\PaddleOCR-main\tools\train.py", line 55, in main
    train_dataloader = build_dataloader(config, "Train", device, logger, seed)
  File "D:\PaddleOCR-main\ppocr\data\__init__.py", line 107, in build_dataloader
    dataset = eval(module_name)(config, mode, logger, seed)
  File "D:\PaddleOCR-main\ppocr\data\simple_dataset.py", line 42, in __init__
    assert (
AssertionError: The length of ratio_list should be the same as the file_list.
```

### 🏃‍♂️ Environment (运行环境)

python 3.10

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

配置文件如图
```yaml
Global:
  use_gpu: false
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_chinese_common_v2.0
  save_epoch_step: 3
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: D:\ancoda\anocada3\envs\paddle\Lib\site-packages\Preliminary_training\ch_ppocr_server_v2.0_rec_train\best_accuracy.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_chinese_common_v2.0.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:\ancoda\anocada3\envs\paddle\Lib\site-packages\train_data\rec\train
    label_file_list: D:\ancoda\anocada3\envs\paddle\Lib\site-packages\train_data\rec\train.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:\ancoda\anocada3\envs\paddle\Lib\site-packages\train_data\rec\val
    label_file_list: D:\ancoda\anocada3\envs\paddle\Lib\site-packages\train_data\rec\val.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 8

```
