### DISCUSSION TITLE
训练kie数据集的时候，默认是200轮，跑到第79轮，cur metric, precision: 0.0, recall: 0.0, hmean: 0.0 这三个参数为0

### DISCUSSION THREAD

**Discussion by freezehe** [PaddlePaddle/PaddleOCR#14403] [Q&A]
### Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.

- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.

- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### Bug

你好，我司正在调研百度飞桨的ppstructure的kie模块，我是在百度的aistudio平台训练kie的模型，参考官方手册一步一步进行的。问题是如标题所示，79轮前面的第78轮都还是正常的，到79轮及以后，cur metric, precision: 0.0, recall: 0.0, hmean: 0.0 三个参数都为0 ，不清楚什么原因。我贴一下截图
![image](https://github.com/user-attachments/assets/f2b2089b-25cc-4404-9c37-b09e9161c098)
![image](https://github.com/user-attachments/assets/0fd78043-97bf-4a20-ad80-008025e10ff5)
请麻烦解答一下，谢谢！我可以提供我的数据集

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by freezehe** [comment]
补充一下，我是训练ser模型任务，执行命令是：! python3 -m paddle.distributed.launch --gpus '0'  tools/train.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml，也下载了官方文档提供的预训练模型

**Comment by UserWangZz** [comment]
你好，之前确实没有遇到过这类情况，可以问一下这个问题是可以复现的吗，还是说是偶然发生？

**Comment by metoogo** [comment]
感觉是官方的预训练模型有问题，我是在win10下跑的，下载的预训练模型tar文件，解压后得到的其实还是个压缩包，修改成.tar或者是.rar后缀再解压一次会得到3个文件，里面有模型model_state.pdparams，但是缺了个.pdopt，所以一般方法直接使用breakpoints导入是用不了的

**Comment by GreatV** [comment]
根据您提供的信息以及 PaddleOCR 的配置和问题描述，以下是关于训练中 `hmean`、`precision` 和 `recall` 一直为 0 的可能原因及解决方法的详细分析和建议：

### 1. **数据集问题**
- **标签文件问题**：检查 `train.txt` 和 `val.txt` 文件中的标签格式是否正确。例如，PaddleOCR 要求的检测标签文件格式通常是 `image_path\t[{"transcription": "text", "points": [[x1, y1], [x2, y2], ...]}]`。请确保标签文件中的标注是有效的，且路径正确。
- **数据不足**：您提到的数据集只有 200 张图像，这可能导致模型训练不足或过拟合，特别是在计算指标（如 `hmean`）时可能会出现问题。建议尝试扩充数据集。
- **图像尺寸问题**：您的图像尺寸为 350x48，比例过于狭长，可能导致模型难以学习有效的特征。建议调整图像尺寸，例如增加高度，或者采用更适合长文本的模型。

### 2. **训练配置问题**
- **`cal_metric_during_train` 设置**：从配置文件中看到 `cal_metric_during_train: false`，这意味着在训练过程中不会计算 `precision`、`recall` 和 `hmean`。如果需要实时监控这些指标，请将其设置为 `true`。
- **`eval_batch_step` 配置**：`eval_batch_step` 参数为 `[0, 50]`，这表示只在第 0 和第 50 个 step 进行评估。如果您希望更频繁地评估训练效果，可以调整此参数，例如 `[50, 100]` 或更小的间隔。
- **`epoch_num` 和 `save_epoch_step`**：您的 `epoch_num` 为 200，但 `save_epoch_step: 100`，这意味着模型的中间结果只会在第 100 和 200 epoch 保存。如果训练在中途异常终止，可能会丢失中间结果。建议缩短 `save_epoch_step` 为 10 或 20。

### 3. **模型架构与输入尺寸的适配性**
- **输入图像尺寸问题**：您的训练数据为 350x48，远小于配置中的 `960x960`（`EastRandomCropData` 的裁剪尺寸）。这种极端的尺寸差异可能导致模型难以适配输入数据，进而影响训练效果。解决方法：
  - 修改 `EastRandomCropData` 的 `size` 参数，使其更接近您的数据尺寸，例如 `350x48` 或 `400x64`。
  - 确保 `Resize` 操作不会过度缩放图像，避免特征丢失。
- **模型适配性**：当前使用的是 `MobileNetV3` 作为骨干网络，且 `scale: 0.5`。对于极狭长的文本，建议尝试使用支持长文本检测的模型，如 `ResNet` 系列，或者使用专门设计的 KIE 模块。

### 4. **后处理与评估问题**
- **后处理参数**：`DBPostProcess` 中的 `thresh` 和 `box_thresh` 参数可能设得过高，导致模型在评估时无法生成有效的检测框。建议降低这些值，例如：
  ```yaml
  thresh: 0.2
  box_thresh: 0.5
  ```
  然后重新运行评估。
- **评估指标计算失败**：如果训练中 `precision`、`recall` 和 `hmean` 为 0，可能是模型预测的结果与标签不匹配，或者完全没有预测输出框。建议：
  - 检查训练日志，看是否有预测输出框。
  - 使用 `debug: true` 模式，观察数据增广和预测结果是否正常。

### 5. **调试与诊断建议**
- **开启调试模式**：将 `Global: debug: false` 修改为 `true`，这样可以在训练过程中输出更多的中间信息，帮助诊断问题。
- **单张图像测试**：使用训练好的模型对单张图像进行推理，检查预测框是否合理。如果推理正常但训练指标为 0，说明问题可能出在评估代码或数据预处理环节。

### 6. **尝试官方建议**
- **参考官方讨论中的类似问题**：根据您提供的相关讨论（[Discussion URL](https://github.com/PaddlePaddle/PaddleOCR/discussions/14250)），也有用户报告类似问题，可能与输入尺寸或标签格式有关。建议详细对比官方提供的示例数据及配置文件。
- **切换 PaddleOCR 版本**：您提到尝试了 v2.7 和 v2.9，但问题仍然存在。建议尝试最新的稳定版本，或切换到适配性更好的分支。

---

### 建议的调整示例
以下是根据您的情况修改后的部分配置：
```yaml
Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:\Users\Czw\Desktop\ocr\det/
    label_file_list:
      - C:\Users\Czw\Desktop\ocr\det\train.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - Resize:
        size:
        - 400  # 调整为更适合数据的尺寸
        - 64
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 4
    num_workers: 2
```

---

### 总结
1. 检查数据集和标签格式，确保其符合 PaddleOCR 的要求。
2. 调整图像尺寸和数据预处理配置，使其更适合您的数据。
3. 修改训练和评估配置，确保 `hmean` 等指标在训练过程中被正确计算。
4. 使用调试模式和单张图像测试，定位问题所在。

如果问题仍未解决，建议提供更多详细日志或最小可复现示例，便于进一步诊断。

---
*Response generated by [feifei-bot](https://github.com/GreatV/feifei) | chatgpt-4o-latest*
