### DISCUSSION TITLE
在文本检测的训练中，如何在yaml配置文件中配置，使得IaaAugment数据增强中的增强方式按几率p执行

### DISCUSSION THREAD

**Discussion by gokamisama** [PaddlePaddle/PaddleOCR#14423] [General]
因为我发现只有Fliplr有p参数，而很多增强源码中没有p参数可以设置，IaaAugment有一个Somtimes类可以用于设置IaaAugment数据增强生效的概率，但是我尝试将其加入配置文件中，但是失败了，可以告知我如何使数据增强按一定的概率生效吗？
```yaml
      - IaaAugment:
          augmenter_args:
            - type: Sometimes
              args:
                p: 0.5
                then_list:
                - type: GaussianBlur  # 应用高斯模糊
                  args:
                    sigma:
                      - 0.0
                      - 0.5
```
报以下错误：`AssertionError: Expected all children to be augmenters, got types <class 'dict'>.`
