### DISCUSSION TITLE
文本检测模型（dbnet）的微调训练可以增加哪些额外的数据增强方式，如何添加？

### DISCUSSION THREAD

**Discussion by gokamisama** [PaddlePaddle/PaddleOCR#14422] [General]
```yaml
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - DetLabelEncode: null
      - IaaAugment:
          augmenter_args:
            - type: Fliplr
              args:
                p: 0.5
            - type: Affine
              args:
                rotate:
                  - -10
                  - 10
            - type: Resize
              args:
                size:
                  - 0.5
                  - 3
      - EastRandomCropData:
          size:
            - 1280
            - 1280
          max_tries: 50
          min_crop_side_ratio: 0.5
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
          order: hwc
      - ToCHWImage: null
      - KeepKeys:
          keep_keys:
            - image
            - threshold_map
            - threshold_mask
            - shrink_map
            - shrink_mask
```

默认的配置文件只有Fliplr/Affine的旋转/Resize，我该如何添加其他的数据增强方式，例如高斯模糊/噪点/透视变换/剪切变换等。希望大佬能够解答我的疑惑，非常感谢！
