### DISCUSSION TITLE
Table Recognition: Training model is transferred to the inference model, the prediction effect is inconsistent?

### DISCUSSION THREAD

**Discussion by vuthehuy1997** [PaddlePaddle/PaddleOCR#14505] [Q&A]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

When I finished training the SLANet recognition table model, I exported it to a format for inference, but the results were wrong. i only edit SLANet.yml to SLANet_finetune.yml like tutorial on github document

Model training command (finetune from model ch_ppstructure_mobile_v2.0_SLANet_train)
```
python3 tools/train.py -c configs/table/SLANet_finetune.yml\
 -o Global.pretrained_model=./weights/whl/table/ch_ppstructure_mobile_v2.0_SLANet_train/best_accuracy \
 Global.use_amp=True Global.scale_loss=1024.0 Global.use_dynamic_loss_scaling=True
```

export command:
```
python3 tools/export_model.py -c configs/table/SLANet_finetune.yml -o Global.pretrained_model=../translate-pdf-scan/src/weights/table_rec/SLANet_ch/best_accuracy Global.save_inference_dir=../translate-pdf-scan/src/weights/table_rec/ch_ppstructure_mobile_v2.0_SLANet_finetune
```

If i run the model after training with the command:
```
python3 tools/infer_table.py -c configs/table/SLANet_finetune.yml -o Global.pretrained_model=../translate-pdf-scan/src/weights/table_rec/SLANet_ch/best_accuracy Global.infer_img=ppstructure/docs/table/table .jpg
```
Then it gives correct results

```
result: ['<html>', '<body>', '<table>', '<tr>', '<td', ' colspan="2"', '>', '</td>', '<td', ' rowspan="2"', '>', '</ td>', '<td', ' colspan="2"', '>', '</td>', '<td', ' rowspan="2"', '>', '</td> ', '<td', ' rowspan="2"', '>', '</td>', '<td', ' rowspan="2"', '>', '</td>', '<td', ' rowspan= "2"', '>', '</td>', '<td', ' rowspan="2"', '>', '</td>', '<td', ' rowspan="2 "', '>', '</td>', '</tr>', '<tr>', '<td></td>', '<td></td>', '<td></td>', '<td></td>', ..., '</table>' , '</body>', '</html>'], [[0.7451880574226379, 1.5897825956344604, 122.04891204833984, 1.5919700860977173, 122.1083755493164, 34.912353515625, 0.7465599775314331, 34.94774627685547], ...
```

If running model was export:
```
cd ppstructure/
python table/predict_structure.py\
 --table_model_dir=../../translate-pdf-scan/src/weights/table_rec/ch_ppstructure_mobile_v2.0_SLANet_finetune \
 --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt \
 --image_dir=docs/table/table.jpg \
 --output=../output/table
```
Then the result will be wrong
```
['<html>', '<body>', '<table>', '</tbody>', '</tbody>', '</tbody>', '</tbody>', '</ tbody>', '</thead>', '</tbody>', '</tbody>', '</thead>', '</thead>', '</tbody>', '</thead >', ..., '<tr>', '</table>', '</body>', '</html>'], [[2.9795612022098794e-07, 2.2673059163480502e-07, 8.608171120361163e-11, 9.731257932799053e-07, 8.894006642279351e-10, 3.4046809105348075e-07, 3.1248458043364735e-08, 17.488468170166016, 9.80240444370395e-10, 8.043410382185812e-09, ...
```

Does anyone know what the error is when exporting?

### 🏃‍♂️ Environment (运行环境)

```
Ubuntu
paddlepaddle_gpu=3.0.0b0
NVIDIA A40
cuda 12.3
```

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

```
Global:
  use_gpu: True
  epoch_num: 400
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/SLANet_ch
  save_epoch_step: 400
  # evaluation is run every 331 iterations after the 0th iteration
  eval_batch_step: [0, 331]
  cal_metric_during_train: True
  pretrained_model: ./weights/whl/table/ch_ppstructure_mobile_v2.0_SLANet_train/best_accuracy.pdparams
  checkpoints: 
  save_inference_dir: ./output/SLANet_ch/infer
  use_visualdl: False
  infer_img: ppstructure/docs/table/table.jpg
  # for data or label process
  character_dict_path: ppocr/utils/dict/table_structure_dict_ch.txt
  character_type: en
  max_text_length: &max_text_length 500
  box_format: &box_format xyxyxyxy # 'xywh', 'xyxy', 'xyxyxyxy'
  infer_mode: False
  use_sync_bn: True
  save_res_path: output/infer
    
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  # lr:
  #   learning_rate: 0.001
  # regularizer:
  #   name: 'L2'
  #   factor: 0.00000
  lr:
    name: Cosine
    learning_rate: 0.00017 #
    warmup_epoch: 0
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: table
  algorithm: SLANet
  Backbone:
    name: PPLCNet
    scale: 1.0
    pretrained: True
    use_ssld: True
  Neck:
    name: CSPPAN
    out_channels: 96
  Head:
    name: SLAHead
    hidden_size: 256
    max_text_length: *max_text_length
    loc_reg_num: &loc_reg_num 8

Loss:
  name: SLALoss
  structure_weight: 1.0
  loc_weight: 2.0
  loc_loss: smooth_l1

PostProcess:
  name: TableLabelDecode
  merge_no_span_structure: &merge_no_span_structure True

Metric:
  name: TableMetric
  main_indicator: acc
  compute_bbox_metric: False
  loc_reg_num: *loc_reg_num
  box_format: *box_format
  del_thead_tbody: True

Train:
  dataset:
    name: PubTabDataSet
    data_dir: ./datasets/train/table/table_envi/
    label_file_list: [./datasets/train/table/table_envi/train.jsonl]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bboxes', 'bbox_masks', 'length', 'shape']
  loader:
    shuffle: True
    batch_size_per_card: 16
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: PubTabDataSet
    data_dir: ./datasets/train/table/table_envi/
    label_file_list: [./datasets/train/table/table_envi/val.jsonl]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'structure', 'bboxes', 'bbox_masks', 'length', 'shape']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 1

```
