### DISCUSSION TITLE
rec模型微调时，原数据要保留多少？新数据要多少？

### DISCUSSION THREAD

**Discussion by nissansz** [PaddlePaddle/PaddleOCR#14768] [Q&A]
rec模型微调时，原数据要保留多少？新数据要多少？

**Comment by GreatV** [comment]
在对 rec（文本识别）模型进行微调时，关于原始数据和新数据的比例，主要有以下建议：

1. **数据量要求**：
   - 如果**不更换字典**，建议至少准备 **5000 张**的文本识别数据用于模型微调。
   - 如果**更换了字典**（不推荐，但如果必须更换），则需要的训练数据量会相对更大，以确保新字典的字符得到充分训练。

2. **数据分布**：
   - 训练数据应尽可能贴近实际使用场景。例如：
     - 如果实际场景包含大量**短文本**，训练数据也应包含更多短文本。
     - 如果实际应用对**空格识别**有较高要求，则训练数据中应加入更多带空格的文本。

3. **合成数据与真实数据的比例**：
   - 为了针对性地提升某些字符的识别能力，可以增加**特定字符**的数据，并使用小学习率进行微调。
   - 通常建议**原始数据与新增数据的比例为 10:1 ~ 5:1**，避免单一数据场景过多造成模型**过拟合**。
   - 需要确保训练数据中的**常用字频率均衡**，防止某些字符出现次数过少影响识别效果。

4. **通用场景数据的加入**：
   - 在训练数据中额外加入通用数据（如 LSVT、RCTW、MTWI 等真实数据）可以**提升模型的泛化能力**。
   - 若使用通用场景数据，建议训练时保持**垂类场景数据：通用真实数据 = 1:1**。

例如：
- **垂类场景数据量 = 1W 条，文件名 `vertical.txt`**  
- **通用场景数据量 = 10W 条，文件名 `general.txt`**
- 通过 `ratio_list` 参数设置每个 epoch 的数据采样比例，使 `vertical.txt` 全部使用（比例 1.0），而 `general.txt` 仅采样 0.1（即 `10W * 0.1 = 1W`），从而确保训练时两类数据均衡：
  ```yaml
  Train:
    dataset:
      name: SimpleDataSet
      data_dir: ./train_data/
      label_file_list:
      - vertical.txt
      - general.txt
      ratio_list: [1.0, 0.1]
  ```

5. **持续优化**：
   - 训练后建议**收集实际 badcase**，有针对性地调整训练数据比例或新增特定数据集，进行多轮迭代优化。
   - 这样可以**逐步提升模型在目标场景中的识别精度**。

总结：如果使用通用数据进行微调，建议保证垂类数据与通用数据比例 1:1；如果是加入特定字符数据进行精调，建议保持原始数据与新增数据比例在 10:1 ~ 5:1 之间，以避免模型过拟合。

---
*Response generated by 🤖 [feifei-bot](https://github.com/GreatV/feifei) | chatgpt-4o-latest*

 ⚠️ This is an AI-generated response. Please verify any critical information.
