### DISCUSSION TITLE
Paddle Serving 的 OCR 服务部署，运行pipeline_http_client.py报错：Segmentation fault

### DISCUSSION THREAD

**Discussion by turndown** [PaddlePaddle/PaddleOCR#14902] [Q&A]
请教大佬们，下面的错误问题要如何解决，我是参考这个链接操作的：https://blog.csdn.net/futureflsl/article/details/139911095

操作系统：欧拉系统   2401.1.0.0233.oe1.x86_64
cuda_12.5.r12.5/compiler.34177558_0
cudnn 9.0.0
conda环境：python 3.9.21 

依赖安装：
pip3 install paddle_serving_server_gpu-0.8.3.post112-py3-none-any.whl
pip3 install paddle_serving_client-0.8.3-cp39-none-any.whl
pip3 install paddle_serving_app-0.8.3-py3-none-any.whl
低版本：paddlepaddle-gpu==2.1.2
paddlepaddle              2.6.2
paddlenlp                 2.8.1

模型：
https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar
https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar

服务运行，用的gpu推理：
python3 web_service.py --config=config.yml &>log.txt &

**最后运行：python3 pipeline_http_client.py，直接卡在那边没有出来结果**

web_service.py的错误日志：
```
/data/paddle-serve/PaddleOCR/deploy/pdserving/web_service.py:61: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, np.uint8)
W0319 14:44:10.014024 277659 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.4, Runtime API Version: 10.2
W0319 14:44:10.015365 277659 device_context.cc:422] device: 0, cuDNN Version: 90.0.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1742366650 (unix time) try "date -d @1742366650" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 277659 (TID 0x7fde4d1df200) from PID 0 ***]
```

**Comment by GreatV** [comment]
你的问题是运行 `pipeline_http_client.py` 时遇到了 `Segmentation fault`（分段错误）。根据你的环境和错误日志，以下几个可能的原因以及相应的解决方案可以尝试：

### **可能原因及解决方案**
#### **1. PaddlePaddle 版本问题**
你的环境中 `paddlepaddle-gpu == 2.1.2` 和 `paddlepaddle == 2.6.2`，这可能导致版本冲突。请尝试：
```bash
pip uninstall paddlepaddle paddlepaddle-gpu
```
然后安装**与 CUDA 12.5 兼容的 GPU 版本**的 `paddlepaddle-gpu`：
```bash
pip install paddlepaddle-gpu==2.6.2.post125
```
（如果 `post125` 版本不可用，尝试 `2.6.1` 或 `2.6.2` 对应的 CUDA 兼容版本）

---

#### **2. CUDA 和 cuDNN 版本不匹配**
从你的日志看：
- **CUDA 版本**：12.5
- **Runtime API Version**：10.2
- **cuDNN 版本**：9.0.0

参考 [PaddlePaddle 官方兼容性文档](https://www.paddlepaddle.org.cn/install/quick)，CUDA 12.5 **通常应该搭配 cuDNN 8.x** 而不是 9.0.0。

**解决方案：**
如果可以，尝试降级 cuDNN，例如 `8.8.x` 版本。

```bash
# 检查已安装 cuDNN
ls /usr/local/cuda/lib64 | grep libcudnn

# 如果需要更换版本，建议使用 NVIDIA 官网指南安装 cuDNN 8.x
```

---

#### **3. web_service.py `fromstring` 代码问题**
日志中有以下警告：
```
DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
```
在 `web_service.py` 文件中，**找到**：
```python
data = np.fromstring(data, np.uint8)
```
并**修改为**：
```python
data = np.frombuffer(data, np.uint8)
```
然后**重启服务**：
```bash
python3 web_service.py --config=config.yml &>log.txt &
```

---

#### **4. 运行 PaddleOCR 相关的 Serving 服务时的 GPU 访问问题**
可以尝试在 `web_service.py` **前加上**环境变量：
```bash
export CUDA_VISIBLE_DEVICES=0
python3 web_service.py --config=config.yml &>log.txt &
```
如果还是 `Segmentation fault`，可以尝试**强制 CPU 运行**：
```bash
export CUDA_VISIBLE_DEVICES=-1
python3 web_service.py --config=config.yml &>log.txt &
```

---

#### **5. 检查 PaddleOCR 模型格式**
参考的 OCR 模型：  
- `ch_PP-OCRv3_det_infer.tar`
- `ch_PP-OCRv3_rec_infer.tar`

请确认这些模型被正确解压，并且 Serving 端正确加载：
```bash
tar -xf ch_PP-OCRv3_det_infer.tar
tar -xf ch_PP-OCRv3_rec_infer.tar
```
并检查 `config.yml` 是否正确指向了解压后的路径。

---

### **结论**
1. **更换 PaddlePaddle 版本**（尝试 `2.6.2.post125`）。
2. **检查 CUDA 和 cuDNN 版本**（降级到 cuDNN 8.8.x）。
3. **修正 `fromstring` 为 `frombuffer`** 并重启服务。
4. **尝试固定 GPU ID 运行** 或者 **强制 CPU 运行** 进行测试。
5. **确保 OCR 模型正确解压可用**。

### **相关讨论**
与你的问题相似的 Discussion：
[Paddle2.6.1 执行任务时报错 Segmentation fault](https://github.com/PaddlePaddle/PaddleOCR/discussions/13903)  
这篇讨论也涉及了 Segmentation fault，可能和 PaddlePaddle 版本或 CUDA 兼容性有关。

你可以逐步尝试这些方法，看看是否能解决你的问题。希望对你有所帮助！🚀

---
*Response generated by 🤖 [feifei-bot](https://github.com/GreatV/feifei) | chatgpt-4o-latest*

 ⚠️ This is an AI-generated response. Please verify any critical information.

**Comment by turndown** [comment]
1.paddlepaddle-gpu的版本如果高了，就报No module named ‘paddle.fluid’的错误；
另外问下paddlepaddle-gpu和paddlepaddle不能同时安装吗？
2.我再试下；
3.ok；
4.配置cpu或gpu运行，我是根据config.yml里来的。device我写的都是gpu 0：
```
[root@ecs-lcdsj pdserving]# cat config.yml
#rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
rpc_port: 30006

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 30003

#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
##当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 10

#build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: False

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False

    #重试次数
    retry: 10

    #使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
    use_profile: True

    tracer:
        interval_s: 10
op:
    det:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 8

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:
            #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #det模型路径
            model_config: ./ppocr_det_v3_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准，不设置默认取全部输出变量
            #fetch_list: ["sigmoid_0.tmp_0"]

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0"

            ir_optim: True
    rec:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 4

        #超时时间, 单位ms
        timeout: -1

        #Serving交互重试次数，默认不重试
        retry: 1

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:

            #client类型，包括brpc, grpc和local_predictor。local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #rec模型路径
            model_config: ./ppocr_rec_v3_serving

            #Fetch结果列表，以client_config中fetch_var的alias_name为准, 不设置默认取全部输出变量
            #fetch_list:

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0"

            ir_optim: True


```
5.模型转换是成功的，没有报错
