### DISCUSSION TITLE
Paddleocr Finetuning pretrained model with custom data doesnt work as expected

### DISCUSSION THREAD

**Discussion by LeonGitafk** [PaddlePaddle/PaddleOCR#14965] [Q&A]
Hello,
iam trying to get the best possible result of text recognition for my specific kind of pictures. I researched in the paddleocr documentation for recognition training and found out that I need to have 100.000+ pictures for my own custom model. I cant do this at this moment tho because I only have acces to 1100 pictures right now. Then I found out about Finetuning a pretrained model like the "en_PP-OCRv3_rec", which needs 5000+ images to get good results, but I thought with 1100 pictures I get a first impression if it works and if I get little changes in the resultating recognition. So I prepared all the data in a Folder called FineTuningOCR like this:
```
C:.
│   best_accuracy.pdparams
│   en_dict.txt
│
├───configs
│   └───rec
│           FineTuning.yml
│
├───result
└───trainData
    │   train.txt
    │
    └───images
             image.jpg
             image2.jpg
             image3.jpg
             ...
             image1100.jpg
```

best_accuracy.pdparams ist the pretrained model. en_dict.txt is the dictionary containing all the symbols. In the trainData Folder the images are located and the train.txt that is in the following scheme: "[pathToPicture/image.jpg][TAB][symbols]" example: "C:/Users/Max/Documents/FineTuning/trainData/images/image.jpg	D-FWFG".
My FineTuning.yml file that guides the training, looks like this:
```
Global:
  use_gpu: True
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: C:/Users/Name/Documents/FineTuningOCR/result/model/
  save_epoch_step: 3
  eval_batch_step: [0, 500]  # Öfter evaluieren für schnelleres Debugging
  cal_metric_during_train: True
  pretrained_model: C:/Users/Name/Documents/FineTuningOCR/best_accuracy.pdparams
  checkpoints:
  save_inference_dir: ./
  use_visualdl: False
  character_dict_path: C:/Users/Name/Documents/FineTuningOCR/en_dict.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: C:/Users/Name/Documents/FineTuningOCR/result/predicts3.txt
  
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    learning_rate: 0.0001  # Höhere Start-LR für stabileres Training
    warmup_epoch: 2
    decay_epochs: [10, 25, 40]
    values: [0.0001, 0.00005, 0.00001, 0.000005]
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/Name/Documents/FineTuningOCR/result/
    label_file_list: ["C:/Users/Name/Documents/FineTuningOCR/trainData/train.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: True
    batch_size_per_card: 8  # Höher für stabileres Training (falls GPU erlaubt)
    drop_last: False
    num_workers: 4
    use_shared_memory: True  # Falls es RAM-Probleme gibt, auf False setzen

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/Name/Documents/FineTuningOCR/trainData/images/
    label_file_list: ["C:/Users/Name/Documents/FineTuningOCR/trainData/train.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 4
    use_shared_memory: True
```

My Hardware is a Nvidia Gtx1650 4GB VRAM GPU and I have 32GB RAM. 

I tried to train it and it seemed that everything worked fine. 
Training command in cmd:
```
cd C:/Users/Name/PaddleOCR
python tools/train.py -c C:/Users/Name/Documents/FineTuningOCR/configs/rec/FineTune.yml
```
I have received a best_model folder in my result/model/ folder which contained "model.pdopt" and "model.pdparams" This filetype couldnt be used as the model so I used the following command to convert:
```
python tools/export_model.py -c C:\Users\Name\Documents\FineTuningOCR\configs\rec\FineTune.yml -o Global.pretrained_model=C:\Users\Name\Documents\FineTuningOCR\best_accuracy.pdparams  Global.save_inference_dir=C:\Users\Name\Documents\FineTuningOCR\FinalModel
```

And got these files: inference.pdiparams, inference.pdiparams.info, inference.pdmodel, inference.yml
This is the content of Inference.yml (I find it suspicious that some letters are not in quotation marks):
```
PreProcess:
  transform_ops:
  - DecodeImage:
      channel_first: false
      img_mode: BGR
  - CTCLabelEncode: null
  - RecResizeImg:
      image_shape:
      - 3
      - 32
      - 100
  - KeepKeys:
      keep_keys:
      - image
      - label
      - length
PostProcess:
  name: CTCLabelDecode
  character_dict:
  - '0'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - ':'
  - ;
  - <
  - '='
  - '>'
  - '?'
  - '@'
  - A
  - B
  - C
  - D
  - E
  - F
  - G
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - O
  - P
  - Q
  - R
  - S
  - T
  - U
  - V
  - W
  - X
  - Y
  - Z
  - '['
  - \
  - ']'
  - ^
  - _
  - '`'
  - a
  - b
  - c
  - d
  - e
  - f
  - g
  - h
  - i
  - j
  - k
  - l
  - m
  - n
  - o
  - p
  - q
  - r
  - s
  - t
  - u
  - v
  - w
  - x
  - y
  - z
  - '{'
  - '|'
  - '}'
  - '~'
  - '!'
  - '"'
  - '#'
  - $
  - '%'
  - '&'
  - ''''
  - (
  - )
  - '*'
  - +
  - ','
  - '-'
  - .
  - /
  - ' '

```

Then I tried this Code:
```
import os
from paddleocr import PaddleOCR

def test_ocr(image_path, model_dir, dict_path):
    ocr_model = PaddleOCR(
        det=False,
        show_log=True,
        use_angle_cls=True,
        det_db_box_thresh=0.6,
        det_db_unclip_ratio=1.8,
        rec_model_dir=model_dir,
        rec_char_dict_path=dict_path
    )

    result = ocr_model.ocr(image_path, cls=True)

    print("Text:")
    for line in result[0]:
        print(f"Text: {line[1][0]} (Confidence: {line[1][1]})")

image_path = "./image.jpg"
model_dir = "./FinalModel"
dict_path = "./en_dict.txt"

test_ocr(image_path, model_dir, dict_path)

```

with the pretrained inference model alone I have a result of the Text shown in the image, while the new Fine tuned model recognizes nothing. I dont understand why. what did I do wrong. I thought it must perform at least as well as the pretrained model.
I also tried more other images and for every picture I tried it had no result. Even the same images I used for the training had no result in recognition. So I think there is a issue in my training process.

ty in advance for dealing with my problem and maybe helping me.
