### ISSUE TITLE
KIE RE任务训练出错

### ISSUE THREAD

**Issue by kerry-weic** [PaddlePaddle/PaddleOCR#10170]
执行训练脚本如下:
```
python3 tools/train.py -c configs/kie/re_vi_layoutxlm_my_tax3_zh.yml
```

报错日志如下:
```
File "tools/train.py", line 209, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 181, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/ocr/PaddleOCR/tools/program.py", line 290, in train
    preds = model(batch)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ocr/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 86, in forward
    x = self.backbone(x)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/ocr/PaddleOCR/ppocr/modeling/backbones/vqa_layoutlm.py", line 227, in forward
    x = self.model(
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1412, in forward
    loss, pred_relations = self.extractor(sequence_output, entities, relations)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1304, in forward
    relations, entities = self.build_relation(relations, entities)
  File "/usr/local/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 1260, in build_relation
    all_possible_relations_repeat = all_possible_relations.unsqueeze(axis=1).tile(
  File "/usr/local/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 3147, in tile
    return _C_ops.tile(x, repeat_times)
ValueError: (InvalidArgument) Every element of the input 'repeat_times' for tile op must be greater than 0, but the value given is 0.
  [Hint: Expected repeat_times_data[i] > 0, but received repeat_times_data[i]:0 <= 0:0.] (at /paddle/paddle/phi/infermeta/unary.cc:3743)
```

训练所使用配置文件(re_vi_layoutxlm_my_tax3_zh.yml):
```
Global:
  use_gpu: False
  epoch_num: &epoch_num 130
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: ./output/re_vi_layoutxlm_my_tax3_zh
  save_epoch_step: 2000
  # evaluation is run every 10 iterations after the 0th iteration
  eval_batch_step: [ 0, 19 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_21.jpg
  save_res_path: ./output/re/my_tax3_zh/with_gt
  kie_rec_model_dir: 
  kie_det_model_dir:

Architecture:
  model_type: kie
  algorithm: &algorithm "LayoutXLM"
  Transform:
  Backbone:
    name: LayoutXLMForRe
    pretrained: True
    mode: vi
    checkpoints:

Loss:
  name: LossFromOutput
  key: loss
  reduction: mean

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10
  lr:
    learning_rate: 0.00005
    warmup_epoch: 10
  regularizer:
    name: L2
    factor: 0.00000
    
PostProcess:
  name: VQAReTokenLayoutLMPostProcess

Metric:
  name: VQAReTokenMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: train_data/my_tax3/train
    label_file_list: 
      - train_data/my_tax3/train.json
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: &class_path train_data/my_tax3/class_list.txt
          use_textline_bbox_info: &use_textline_bbox_info True
          order_method: &order_method "tb-yx"
      - VQATokenPad:
          max_seq_len: &max_seq_len 512
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
          entities_labels: &entities_labels {'ADDRESS_PHONE_KEY': 0, 'ADDRESS_PHONE_VALUE': 1, 'BANK_ACCOUNT_KEY': 2, 'BANK_ACCOUNT_VALUE': 3, 'IDENTIFY_NUMBER_KEY': 4, 'IDENTIFY_NUMBER_VALUE': 5, 'MONEY_KEY': 6, 'MONEY_VALUE': 7, 'NAME_KEY': 8, 'NAME_VALUE': 9, 'NO_KEY': 10, 'NO_VALUE': 11, 'PRICE_KEY': 12, 'PRICE_VALUE': 13, 'SELLER_NAME_KEY': 14, 'SELLER_NAME_VALUE': 15, 'SERVER_KEY': 16, 'SERVER_VALUE': 17, 'TOTAL_PRICE_KEY': 18, 'TOTAL_PRICE_VALUE': 19}
      - TensorizeEntitiesRelations:
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox','attention_mask', 'token_type_ids', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 1
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: train_data/my_tax3/val
    label_file_list:
      - train_data/my_tax3/val.json
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: True
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: *use_textline_bbox_info
          order_method: *order_method
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQAReTokenRelation:
      - VQAReTokenChunk:
          max_seq_len: *max_seq_len
          entities_labels: *entities_labels
      - TensorizeEntitiesRelations:
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'entities', 'relations'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 8
    num_workers: 8
```

自定义字典数据:
```
OTHER
ADDRESS_PHONE_KEY
ADDRESS_PHONE_VALUE
BANK_ACCOUNT_KEY
BANK_ACCOUNT_VALUE
IDENTIFY_NUMBER_KEY
IDENTIFY_NUMBER_VALUE
MONEY_KEY
MONEY_VALUE
NAME_KEY
NAME_VALUE
NO_KEY
NO_VALUE
PRICE_KEY
PRICE_VALUE
SELLER_NAME_KEY
SELLER_NAME_VALUE
SERVER_KEY
SERVER_VALUE
TOTAL_PRICE_KEY
TOTAL_PRICE_VALUE
```

自定义训练标注数据集（随机两条）:
```
b58.jpg	[{"transcription":"4400154130","label":"other","points":[[3657,376],[4007,386],[4005,466],[3655,456]],"id":0,"linking":[]},{"transcription":"国统","label":"other","points":[[2012,473],[2123,449],[2134,498],[2023,522]],"id":1,"linking":[]},{"transcription":"12269540","label":"other","points":[[3667,476],[4003,455],[4008,535],[3672,555]],"id":2,"linking":[]},{"transcription":"聘4400154130","label":"other","points":[[687,493],[1440,469],[1443,562],[690,586]],"id":3,"linking":[]},{"transcription":"东","label":"other","points":[[2271,536],[2310,536],[2310,572],[2271,572]],"id":4,"linking":[]},{"transcription":"开票日期：","label":"other","points":[[3081,590],[3487,575],[3490,651],[3083,666]],"id":5,"linking":[]},{"transcription":"2016年06月12日","label":"other","points":[[3475,582],[3947,562],[3950,637],[3478,657]],"id":6,"linking":[]},{"transcription":"8-94-5806721264<295790517","label":"other","points":[[2646,794],[3894,735],[3898,810],[2650,870]],"id":7,"linking":[]},{"transcription":"C","label":"other","points":[[61,838],[140,838],[140,913],[61,913]],"id":8,"linking":[]},{"transcription":"8810+388149>+4-83-223+<27++","label":"other","points":[[2646,870],[3899,810],[3902,881],[2650,941]],"id":9,"linking":[]},{"transcription":"购","label":"other","points":[[416,895],[473,895],[473,971],[416,971]],"id":10,"linking":[]},{"transcription":"0624+>293/-9>57>16<80>2913-","label":"other","points":[[2651,945],[3903,881],[3907,956],[2654,1021]],"id":11,"linking":[]},{"transcription":"买","label":"other","points":[[416,993],[478,993],[478,1068],[416,1068]],"id":12,"linking":[]},{"transcription":"0413-+<0+38+14+785>4++24+7+","label":"other","points":[[2651,1021],[3912,956],[3916,1031],[2654,1096]],"id":13,"linking":[]},{"transcription":"税总函","label":"other","points":[[276,1064],[368,1064],[368,1334],[276,1334]],"id":14,"linking":[]},{"transcription":"区","label":"other","points":[[2538,1059],[2573,1059],[2573,1104],[2538,1104]],"id":15,"linking":[]},{"transcription":"第二联","label":"other","points":[[4097,1062],[4176,1058],[4187,1269],[4108,1273]],"id":16,"linking":[]},{"transcription":"方","label":"other","points":[[416,1099],[473,1099],[473,1166],[416,1166]],"id":17,"linking":[]},{"transcription":"税率","label":"other","points":[[3371,1108],[3533,1108],[3533,1188],[3371,1188]],"id":18,"linking":[]},{"transcription":"税","label":"other","points":[[3695,1104],[3870,1104],[3870,1170],[3695,1170]],"id":19,"linking":[]},{"transcription":"额","label":"other","points":[[3870,1099],[3945,1099],[3945,1161],[3870,1161]],"id":20,"linking":[]},{"transcription":"数量","label":"other","points":[[2152,1170],[2332,1170],[2332,1250],[2152,1250]],"id":21,"linking":[]},{"transcription":"单位","label":"other","points":[[1876,1183],[2008,1183],[2008,1254],[1876,1254]],"id":22,"linking":[]},{"transcription":"规格型号","label":"other","points":[[1449,1202],[1733,1186],[1737,1262],[1454,1278]],"id":23,"linking":[]},{"transcription":"507.82","label":"other","points":[[3896,1202],[4087,1191],[4091,1258],[3899,1269]],"id":24,"linking":[]},{"transcription":"17%","label":"other","points":[[3432,1219],[3542,1219],[3542,1285],[3432,1285]],"id":25,"linking":[]},{"transcription":"个","label":"other","points":[[1942,1290],[1999,1290],[1999,1356],[1942,1356]],"id":26,"linking":[]},{"transcription":"【2015】600号海南华森实业公司","label":"other","points":[[276,1307],[368,1308],[364,2367],[272,2366]],"id":27,"linking":[]},{"transcription":"抵扣联","label":"other","points":[[4119,1298],[4198,1292],[4207,1530],[4134,1535]],"id":28,"linking":[]},{"transcription":"红米3","label":"other","points":[[1383,1309],[1557,1297],[1562,1377],[1389,1389]],"id":29,"linking":[]},{"transcription":"购","label":"other","points":[[4160,1551],[4204,1551],[4204,1618],[4160,1618]],"id":30,"linking":[]},{"transcription":"￥507.82","label":"other","points":[[3825,1822],[4153,1807],[4157,1887],[3829,1902]],"id":31,"linking":[]},{"transcription":"2987.18","label":"other","points":[[3032,1853],[3408,1838],[3411,1914],[3035,1929]],"id":32,"linking":[]},{"transcription":"计","label":"other","points":[[1021,1937],[1100,1937],[1100,2016],[1021,2016]],"id":33,"linking":[]},{"transcription":"合","label":"other","points":[[653,1954],[736,1954],[736,2030],[653,2030]],"id":34,"linking":[]},{"transcription":"（小写）","label":"other","points":[[3125,1963],[3401,1963],[3401,2039],[3125,2039]],"id":35,"linking":[]},{"transcription":"会仟肆佰玖拾伍圆整","label":"other","points":[[1485,2053],[2203,2020],[2206,2096],[1488,2128]],"id":36,"linking":[]},{"transcription":"dd42980850470(000011968)","label":"other","points":[[2717,2146],[3479,2113],[3481,2175],[2719,2208]],"id":37,"linking":[]},{"transcription":"销","label":"other","points":[[416,2265],[478,2265],[478,2340],[416,2340]],"id":38,"linking":[]},{"transcription":"91440101664041243T","label":"other","points":[[1147,2305],[2141,2255],[2145,2330],[1151,2381]],"id":39,"linking":[]},{"transcription":"纳税人识别号：","label":"other","points":[[534,2318],[984,2299],[988,2379],[537,2399]],"id":40,"linking":[]},{"transcription":"注","label":"other","points":[[2595,2353],[2669,2353],[2669,2433],[2595,2433]],"id":41,"linking":[]},{"transcription":"售","label":"other","points":[[416,2371],[473,2371],[473,2451],[416,2451]],"id":42,"linking":[]},{"transcription":"地址电话：","label":"other","points":[[534,2407],[985,2392],[987,2468],[536,2483]],"id":43,"linking":[]},{"transcription":"广州市黄埔区九龙镇九龙工业园凤凰三横路99号 66215500","label":"other","points":[[1064,2398],[2439,2334],[2443,2415],[1068,2478]],"id":44,"linking":[]},{"transcription":"发票专用章","label":"other","points":[[3585,2410],[3963,2469],[3946,2580],[3568,2521]],"id":45,"linking":[]},{"transcription":"方","label":"other","points":[[421,2491],[478,2491],[478,2562],[421,2562]],"id":46,"linking":[]},{"transcription":"开户行及账号：","label":"other","points":[[534,2500],[984,2481],[987,2557],[537,2576]],"id":47,"linking":[]},{"transcription":"工行北京路支行3602000919200384952","label":"other","points":[[1068,2500],[2211,2441],[2215,2517],[1072,2576]],"id":48,"linking":[]},{"transcription":"销售","label":"other","points":[[3264,2492],[3428,2480],[3434,2564],[3270,2577]],"id":49,"linking":[]},{"transcription":"开票人：陈秋兼","label":"other","points":[[2353,2518],[2905,2503],[2907,2592],[2355,2607]],"id":50,"linking":[]},{"transcription":"复核：张雪","label":"other","points":[[1524,2563],[1908,2542],[1913,2631],[1529,2652]],"id":51,"linking":[]},{"transcription":"(2)","label":"other","points":[[3695,2562],[3822,2562],[3822,2632],[3695,2632]],"id":52,"linking":[]},{"transcription":"收款人：王梅","label":"other","points":[[442,2615],[898,2605],[899,2685],[444,2695]],"id":53,"linking":[]},{"transcription":"地址、电话：","label":"address_phone_key","points":[[534,1028],[968,1019],[969,1099],[536,1109]],"id":54,"linking":[[54,55]]},{"transcription":"深圳市龙华新区民治街道民治大道雁酒科技大虞#12070755-23806606","label":"address_phone_value","points":[[1047,1042],[2409,992],[2412,1054],[1049,1104]],"id":55,"linking":[[54,55]]},{"transcription":"开户行及账号：","label":"bank_account_key","points":[[538,1131],[971,1116],[974,1191],[541,1206]],"id":56,"linking":[[56,57]]},{"transcription":"中国工商银行股份有限公司深圳园岭支行4000024709200172809","label":"bank_account_value","points":[[1047,1126],[2484,1076],[2486,1151],[1049,1202]],"id":57,"linking":[[56,57]]},{"transcription":"纳税人识别号：","label":"identify_number_key","points":[[538,940],[967,925],[970,1001],[541,1016]],"id":58,"linking":[[58,59]]},{"transcription":"440300083885931","label":"identify_number_value","points":[[1104,940],[1900,908],[1903,983],[1107,1016]],"id":59,"linking":[[58,59]]},{"transcription":"金额","label":"money_key","points":[[2954,1126],[3215,1126],[3215,1201],[2954,1201]],"id":60,"linking":[[60,61]]},{"transcription":"2987.18","label":"money_value","points":[[3137,1229],[3368,1218],[3372,1293],[3141,1304]],"id":61,"linking":[[60,61]]},{"transcription":"名称","label":"name_key","points":[[559,826],[948,826],[948,911],[559,911]],"id":62,"linking":[[62,63]]},{"transcription":"深圳市购机汇网络有限公司","label":"name_value","points":[[1042,852],[1782,823],[1785,899],[1045,927]],"id":63,"linking":[[62,63]]},{"transcription":"No","label":"no_key","points":[[2929,371],[3078,371],[3078,485],[2929,485]],"id":64,"linking":[[64,65]]},{"transcription":"12269540","label":"no_value","points":[[3122,363],[3681,363],[3681,474],[3122,474]],"id":65,"linking":[[64,65]]},{"transcription":"单价","label":"price_key","points":[[2510,1153],[2701,1142],[2706,1227],[2515,1238]],"id":66,"linking":[[66,67]]},{"transcription":"597.43589744","label":"price_value","points":[[2489,1268],[2790,1253],[2793,1315],[2492,1331]],"id":67,"linking":[[66,67]]},{"transcription":"名称","label":"seller_name_key","points":[[544,2215],[952,2215],[952,2305],[544,2305]],"id":68,"linking":[[68,69]]},{"transcription":"广州晶东贸易有限公司","label":"seller_name_value","points":[[1064,2222],[1702,2179],[1707,2254],[1068,2297]],"id":69,"linking":[[68,69]]},{"transcription":"货物或应税劳务、服务名称","label":"server_key","points":[[486,1237],[1256,1209],[1259,1280],[488,1308]],"id":70,"linking":[[70,71],[70,72]]},{"transcription":"小米 红米 3全网通版 时尚金色","label":"server_value","points":[[459,1344],[1317,1306],[1320,1382],[462,1419]],"id":71,"linking":[[70,71]]},{"transcription":"移动联通电信4G手机 双卡双待","label":"server_value","points":[[467,1423],[1255,1391],[1257,1453],[469,1485]],"id":72,"linking":[[70,72]]},{"transcription":"价税合计（大写）","label":"total_price_key","points":[[591,2088],[1146,2064],[1150,2140],[594,2164]],"id":73,"linking":[[73,74]]},{"transcription":"￥3495.00","label":"total_price_value","points":[[3423,1964],[3851,1949],[3854,2025],[3425,2039]],"id":74,"linking":[[73,74]]}]
b46.jpg	[{"transcription":"4400154130","label":"other","points":[[3657,274],[4025,284],[4022,364],[3655,354]],"id":0,"linking":[]},{"transcription":"品4400154130","label":"other","points":[[447,346],[1270,332],[1272,438],[448,453]],"id":1,"linking":[]},{"transcription":"12270282","label":"other","points":[[3668,368],[4014,358],[4016,438],[3670,448]],"id":2,"linking":[]},{"transcription":"东","label":"other","points":[[2170,425],[2209,425],[2209,465],[2170,465]],"id":3,"linking":[]},{"transcription":"2016年06月12日","label":"other","points":[[3458,483],[3961,469],[3963,545],[3460,559]],"id":4,"linking":[]},{"transcription":"开票日期：","label":"other","points":[[3037,506],[3395,491],[3398,566],[3040,582]],"id":5,"linking":[]},{"transcription":"/99/5+++4324814+85/9/*95435","label":"other","points":[[2577,697],[3904,655],[3906,731],[2579,772]],"id":6,"linking":[]},{"transcription":"3<+983895808**780*3958/9>7<","label":"other","points":[[2577,776],[3909,735],[3911,810],[2579,852]],"id":7,"linking":[]},{"transcription":"购","label":"other","points":[[167,798],[224,798],[224,860],[167,860]],"id":8,"linking":[]},{"transcription":"码","label":"other","points":[[2437,855],[2485,855],[2485,895],[2437,895]],"id":9,"linking":[]},{"transcription":"3150>/2+2*4--02985***4/998-","label":"other","points":[[2577,856],[3913,815],[3915,890],[2579,931]],"id":10,"linking":[]},{"transcription":"买","label":"other","points":[[162,900],[224,900],[224,975],[162,975]],"id":11,"linking":[]},{"transcription":"55310*59838-5830</349/3>*+9","label":"other","points":[[2577,931],[3926,890],[3928,966],[2579,1007]],"id":12,"linking":[]},{"transcription":"税总","label":"other","points":[[13,975],[96,975],[96,1148],[13,1148]],"id":13,"linking":[]},{"transcription":"方","label":"other","points":[[162,1015],[215,1015],[215,1077],[162,1077]],"id":14,"linking":[]},{"transcription":"税率","label":"other","points":[[3340,1064],[3502,1064],[3502,1148],[3340,1148]],"id":15,"linking":[]},{"transcription":"税额","label":"other","points":[[3677,1055],[3952,1045],[3955,1125],[3680,1135]],"id":16,"linking":[]},{"transcription":"单位","label":"other","points":[[1736,1121],[1872,1121],[1872,1192],[1736,1192]],"id":17,"linking":[]},{"transcription":"数量","label":"other","points":[[2019,1114],[2215,1102],[2219,1182],[2024,1194]],"id":18,"linking":[]},{"transcription":"规格型号","label":"other","points":[[1270,1131],[1572,1120],[1574,1201],[1273,1211]],"id":19,"linking":[]},{"transcription":"507.82","label":"other","points":[[3906,1152],[4098,1152],[4098,1219],[3906,1219]],"id":20,"linking":[]},{"transcription":"17%","label":"other","points":[[3406,1166],[3520,1166],[3520,1236],[3406,1236]],"id":21,"linking":[]},{"transcription":"个","label":"other","points":[[1797,1214],[1876,1214],[1876,1290],[1797,1290]],"id":22,"linking":[]},{"transcription":"红米3","label":"other","points":[[1205,1228],[1390,1228],[1390,1307],[1205,1307]],"id":23,"linking":[]},{"transcription":"抵","label":"other","points":[[4122,1307],[4188,1290],[4207,1366],[4141,1383]],"id":24,"linking":[]},{"transcription":"扣","label":"other","points":[[4142,1356],[4207,1356],[4207,1462],[4142,1462]],"id":25,"linking":[]},{"transcription":"联","label":"other","points":[[4151,1440],[4204,1440],[4204,1511],[4151,1511]],"id":26,"linking":[]},{"transcription":"￥507.82","label":"other","points":[[3813,1813],[4154,1803],[4156,1878],[3815,1889]],"id":27,"linking":[]},{"transcription":"￥2987.18","label":"other","points":[[2972,1835],[3366,1835],[3366,1910],[2972,1910]],"id":28,"linking":[]},{"transcription":"计","label":"other","points":[[793,1923],[872,1923],[872,2003],[793,2003]],"id":29,"linking":[]},{"transcription":"合","label":"other","points":[[403,1937],[478,1937],[478,2016],[403,2016]],"id":30,"linking":[]},{"transcription":"（小写）","label":"other","points":[[3060,1977],[3318,1977],[3318,2056],[3060,2056]],"id":31,"linking":[]},{"transcription":"实","label":"other","points":[[13,2021],[79,2021],[79,2132],[13,2132]],"id":32,"linking":[]},{"transcription":"叁仟肆佰玖拾伍圆整","label":"other","points":[[1297,2030],[2076,2007],[2078,2083],[1299,2106]],"id":33,"linking":[]},{"transcription":"业公","label":"other","points":[[9,2110],[75,2110],[75,2300],[9,2300]],"id":34,"linking":[]},{"transcription":"dd42981327948（00001,1951497145","label":"other","points":[[2625,2145],[3628,2118],[3630,2180],[2627,2208]],"id":35,"linking":[]},{"transcription":"销","label":"other","points":[[136,2265],[215,2265],[215,2344],[136,2344]],"id":36,"linking":[]},{"transcription":"dy","label":"other","points":[[13,2291],[70,2291],[70,2353],[13,2353]],"id":37,"linking":[]},{"transcription":"91440101664041243T","label":"other","points":[[928,2305],[2001,2259],[2004,2335],[931,2381]],"id":38,"linking":[]},{"transcription":"纳税人识别号：","label":"other","points":[[271,2323],[749,2313],[750,2393],[273,2403]],"id":39,"linking":[]},{"transcription":"售","label":"other","points":[[136,2375],[210,2375],[210,2464],[136,2464]],"id":40,"linking":[]},{"transcription":"广州市黄埔区九龙镇九龙工业园凤凰三横路99号 66215500","label":"other","points":[[827,2394],[2326,2343],[2329,2432],[830,2483]],"id":41,"linking":[]},{"transcription":"注","label":"other","points":[[2494,2402],[2555,2402],[2555,2469],[2494,2469]],"id":42,"linking":[]},{"transcription":"地址电话：","label":"other","points":[[272,2415],[758,2415],[758,2491],[272,2491]],"id":43,"linking":[]},{"transcription":"方","label":"other","points":[[140,2504],[202,2504],[202,2575],[140,2575]],"id":44,"linking":[]},{"transcription":"开户行及账号：","label":"other","points":[[271,2513],[757,2503],[759,2583],[273,2593]],"id":45,"linking":[]},{"transcription":"工行北京路支行3602000919200384952","label":"other","points":[[836,2509],[2067,2459],[2070,2534],[839,2585]],"id":46,"linking":[]},{"transcription":"爱票专用章","label":"other","points":[[3568,2526],[3985,2438],[4015,2584],[3598,2672]],"id":47,"linking":[]},{"transcription":"销售","label":"other","points":[[3204,2544],[3371,2544],[3371,2628],[3204,2628]],"id":48,"linking":[]},{"transcription":"开票人：陈秋燕","label":"other","points":[[2220,2573],[2814,2529],[2821,2622],[2227,2665]],"id":49,"linking":[]},{"transcription":"复核：张雪","label":"other","points":[[1321,2608],[1739,2568],[1747,2657],[1330,2697]],"id":50,"linking":[]},{"transcription":"(5)","label":"other","points":[[3771,2630],[3899,2612],[3909,2683],[3781,2702]],"id":51,"linking":[]},{"transcription":"收款人：王梅","label":"other","points":[[160,2643],[649,2608],[655,2701],[167,2736]],"id":52,"linking":[]},{"transcription":"地址、电话：","label":"address_phone_key","points":[[285,935],[753,930],[754,1010],[285,1015]],"id":53,"linking":[[53,54]]},{"transcription":"深圳市龙华新区民治街道民治大道展酒科技大晨412070755-23806606","label":"address_phone_value","points":[[832,931],[2313,899],[2315,970],[834,1002]],"id":54,"linking":[[53,54]]},{"transcription":"开户行及账号：","label":"bank_account_key","points":[[288,1047],[752,1032],[755,1107],[291,1122]],"id":55,"linking":[[55,56]]},{"transcription":"中国工商银行股份有限公司深圳园岭支行4000024709200172809","label":"bank_account_value","points":[[837,1029],[2392,1001],[2394,1077],[838,1104]],"id":56,"linking":[[55,56]]},{"transcription":"纳税人识别号：","label":"identify_number_key","points":[[293,838],[752,824],[755,899],[295,914]],"id":57,"linking":[[57,58]]},{"transcription":"440300083885931","label":"identify_number_value","points":[[903,825],[1761,811],[1763,886],[904,900]],"id":58,"linking":[[57,58]]},{"transcription":"金额","label":"money_key","points":[[2884,1071],[3155,1071],[3155,1161],[2884,1161]],"id":59,"linking":[[59,60]]},{"transcription":"2987.18","label":"money_value","points":[[3095,1174],[3331,1174],[3331,1250],[3095,1250]],"id":60,"linking":[[59,60]]},{"transcription":"名称","label":"name_key","points":[[302,715],[711,715],[711,807],[302,807]],"id":61,"linking":[[61,62]]},{"transcription":"深圳市购机汇网络有限公司","label":"name_value","points":[[832,732],[1638,713],[1640,784],[834,803]],"id":62,"linking":[[61,62]]},{"transcription":"No","label":"no_key","points":[[2874,263],[3022,263],[3022,404],[2874,404]],"id":63,"linking":[[63,64]]},{"transcription":"12270282","label":"no_value","points":[[3070,241],[3670,241],[3670,393],[3070,393]],"id":64,"linking":[[63,64]]},{"transcription":"单价","label":"price_key","points":[[2428,1095],[2621,1095],[2621,1179],[2428,1179]],"id":65,"linking":[[65,66]]},{"transcription":"597.43589744","label":"price_value","points":[[2393,1202],[2721,1192],[2723,1258],[2395,1268]],"id":66,"linking":[[65,66]]},{"transcription":"名称","label":"seller_name_key","points":[[281,2226],[718,2226],[718,2304],[281,2304]],"id":67,"linking":[[67,68]]},{"transcription":"广州晶东贸易有限公司","label":"seller_name_value","points":[[836,2208],[1528,2175],[1531,2251],[840,2284]],"id":68,"linking":[[67,68]]},{"transcription":"货物或应税劳务、服务名称","label":"server_key","points":[[236,1157],[1059,1134],[1061,1209],[238,1233]],"id":69,"linking":[[69,70],[69,71]]},{"transcription":"小米 红米 3全网通版 时尚金色","label":"server_value","points":[[205,1259],[1117,1235],[1119,1311],[207,1334]],"id":70,"linking":[[69,70]]},{"transcription":"移动联通电信4G手机 双卡双待","label":"server_value","points":[[210,1334],[1055,1311],[1057,1387],[212,1410]],"id":71,"linking":[[69,71]]},{"transcription":"价税合计（大写）","label":"total_price_key","points":[[332,2075],[919,2056],[921,2136],[335,2155]],"id":72,"linking":[[72,73]]},{"transcription":"￥3495.00","label":"total_price_value","points":[[3387,1964],[3842,1945],[3845,2020],[3390,2040]],"id":73,"linking":[[72,73]]}]
```

尝试将自定义字典修改成OTHER、QUESTION、ANSWER后，并修改对应的训练数据集数据和去除配置文件(re_vi_layoutxlm_my_tax3_zh.yml)中 entities_labels 自定义字典配置值后可正常执行训练任务，请问这个问题是出在训练配置文件中还是什么，望指教。谢谢~

paddle相关包版本信息如下:
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/49382323/92c74c58-7c85-434a-a8b2-0fefea84c9eb)
