### ISSUE TITLE
文本识别数据加载怎么设置多个数据集以及设置每个数据集的采样比率

### ISSUE THREAD

**Issue by lipeng1109** [PaddlePaddle/PaddleOCR#10588]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
- 运行指令/Command Code：
- 完整报错/Complete Error Message：

训练LVTR模型，使用了多个不同的数据集，希望每个数据集数据采样数量是不一样的，请问需要怎么做

**Comment by UserWangZz** [comment]
```
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/icdar2015/text_localization/
    label_file_list:
      - ./train_data/icdar2015/text_localization/train_icdar2015_label.txt
    ratio_list: [1.0]
    transforms:
    - DecodeImage:
```
在label_file_list字段中，列出所有的数据集label
ratio_list字段按label_file_list顺序给出每个数据集的采样比例，paddleocr会随机对数据集进行采样
