### ISSUE TITLE
SLANet精调调整scale参数为2.5报错，同预训练模型无法匹配？

### ISSUE THREAD

**Issue by bekars** [PaddlePaddle/PaddleOCR#11745]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
Ubuntu 22.04

- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
PaddleOCR：2.7最新版

- 运行指令/Command Code：
python3 -m paddle.distributed.launch --gpus '0,1' tools/train.py -c /opt/works/train_model/SLANet_ch.yml

- 完整报错/Complete Error Message：
[2024/03/15 10:18:09] ppocr WARNING: The shape of model params backbone.conv1.conv.weight [40, 3, 3, 3] not matched with loaded params backbone.conv1.conv.weight [16, 3, 3, 3] !
[2024/03/15 10:18:09] ppocr WARNING: The shape of model params backbone.conv1.bn.weight [40] not matched with loaded params backbone.conv1.bn.weight [16] !
[2024/03/15 10:18:09] ppocr WARNING: The shape of model params backbone.conv1.bn.bias [40] not matched with loaded params backbone.conv1.bn.bias [16] !
[2024/03/15 10:18:09] ppocr WARNING: The shape of model params backbone.conv1.bn._mean [40] not matched with loaded params backbone.conv1.bn._mean [16] !
[2024/03/15 10:18:09] ppocr WARNING: The shape of model params backbone.conv1.bn._variance [40] not matched with loaded params backbone.conv1.bn._variance [16] !
[2024/03/15 10:18:09] ppocr WARNING: The shape of model params backbone.blocks2.0.dw_conv.conv.weight [40, 1, 3, 3] not matched with loaded params backbone.blocks2.0.dw_conv.conv.weight [16, 1, 3, 3] !
[2024/03/15 10:18:09] ppocr WARNING: The shape of model params backbone.blocks2.0.dw_conv.bn.weight [40] not matched with loaded params backbone.blocks2.0.dw_conv.bn.weight [16] !

请尽量不要包含图片在问题中/Please try to not include the image in the issue.

希望提升表格的识别精度，修改PPLCNet的scale为2.5，但是加载的预训练模型ch_ppstructure_mobile_v2.0_SLANet里scale是1，请问哪里可以下载到scale是2.5的预训练模型？还是只能自己从头训练吗？

```
Architecture:
  model_type: table
  algorithm: SLANet
  Backbone:
    name: PPLCNet
    scale: 2.5      #1.0 改了这里
    pretrained: True
    use_ssld: True
  Neck:
    name: CSPPAN
    out_channels: 96
  Head:
    name: SLAHead
    hidden_size: 256
    max_text_length: *max_text_length
    loc_reg_num: &loc_reg_num 8
```
