### ISSUE TITLE
PaddleOCR use with COG

### ISSUE THREAD

**Issue by adbmdp** [PaddlePaddle/PaddleOCR#12141]
Hello,

I'm trying to build a COG with PaddleOCR on my Macbook Pro (to test locally and the deploy to Replicate).
I tried lots of different configurations but I can't do it. Most of the time, I have this error:

`ⅹ Failed to get type signature: exit status 132`

Here is the last one i've tried :

```
build:
  gpu: false
  system_packages:
    - "ffmpeg"
    - "libsm6"
    - "libxext6"
    - "libgl1-mesa-glx"
    - "poppler-utils"
  python_version: "3.8"
  python_packages:
    - torch
    - torchvision
    - transformers
    - pillow
    - numpy
    - pandas
    - opencv-python
    - PyMuPDF
    - xlsxwriter
    - beautifulsoup4
    - paddleocr>=2.0.1

  run:
    - apt-get update
    - apt-get install -y ffmpeg libsm6 libxext6
    - python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple

predict: "predict.py:Predictor"
```

Any help much appreciated!
