### ISSUE TITLE
How to push paddleOCR to Replicate

### ISSUE THREAD

**Issue by adbmdp** [PaddlePaddle/PaddleOCR#12153]
Hello,

I'm trying to push my model on Replicate but I got this error :
`ⅹ Failed to get type signature: exit status 132`

Here is my cog.yaml file:
```
build:
  gpu: true

  system_packages:
    - libgl1-mesa-glx

  python_version: "3.11"

  python_packages:
    - pydantic
    - pillow
    - numpy
    - opencv-python
    - paddlepaddle-gpu
    - "paddleocr>=2.0.1"

predict: "predict.py:Predictor"
```

On Replicate I can choose between this GPU:

<img width="240" alt="image" src="https://github.com/PaddlePaddle/PaddleOCR/assets/24914102/b5f9002c-29c3-444f-9d15-e801b05f98f2">

Did I forgot something. Or PaddleOCR is not compatible with this GPU?
Thanks a lot for any help.
