### ISSUE TITLE
请放宽 paddleocr==2.9.1 对 albumentations==1.4.10 的硬性限制，谢谢！

### ISSUE THREAD

**Issue by hongbo-miao** [PaddlePaddle/PaddleOCR#14433]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

目前，paddleocr==2.9.1 对 albumentations==1.4.10 的依赖是一个硬性限制。
请把条件放宽，比如修改为 albumentations~=1.4.10。谢谢！

```
uv run poe dev
  × No solution found when resolving dependencies for split (python_full_version >= '3.12.0' and
  │ python_full_version < '3.13' and platform_system == 'Darwin' and sys_platform == 'darwin'):
  ╰─▶ Because doclayout-yolo==0.0.2 depends on albumentations>=1.4.11 and paddleocr==2.9.1 depends on
      albumentations==1.4.10, we can conclude that doclayout-yolo==0.0.2 and paddleocr==2.9.1 are incompatible.
      And because your project depends on doclayout-yolo==0.0.2 and paddleocr==2.9.1, we can conclude that your
      project's requirements are unsatisfiable.
```

### 🏃‍♂️ Environment (运行环境)

Python 3.12
CUDA 12.4
PaddleOCR 2.91

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

pyproject.toml

```toml
[project]
name = "mineru"
version = "1.0.0"
requires-python = "~=3.12.0"
dependencies = [
  "doclayout-yolo==0.0.2",
  "paddleocr==2.9.1",
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
```

然后跑 `uv sync --dev`.
