### ISSUE TITLE
predict_system.py  推理和   C++ 推理问题

### ISSUE THREAD

**Issue by DH-0988** [PaddlePaddle/PaddleOCR#14717]
### 🔎 Search before asking

- [x] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [x] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [x] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

问题一：
det用的yml    det_r50_db++_icdar15.yml          
修改了以下参数
```
pretrained_model: ResNet50_dcn_asf_synthtext_pretrained.pdparams
unclip_ratio: 3.0  
det_box_type: 'poly'
EastRandomCropData:
        size:
        - 640
        - 640
DetResizeForTest:
        image_shape:
        - 640
        - 640
```

rec用的yml    en_PP-OCRv3_rec.yml     没修改官方参数  【3， 48， 320】

用export_model.py导出模型后，用 predict_det.py  和  predict_rec.py   单独测试准确率基本达到99%，但是用串联的方式predict_system.py测试，准确率不足10%（utility.py  参数设置和训练时一样了）。

问题二：
根据官方提供的C++库和代码，加载上面两个网络训练好的模型，DB++  文本检测框一个都检测不出（用ch_PP-OCRv3_det_cml.yml标注的矩形框训练的模型可以正常检出），请问C++版本推理  是否支持  DB++  检出  和   SVTR_LCNet 识别的组合及DB++为何不能正常输出检测框。

希望解答！！！
 

### 🏃‍♂️ Environment (运行环境)

python=3.12
paddleocr=2.9.1
paddlepaddle-gpu=2.6.1
cuda=11.8

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

官方代码 predict_system.py
