### ISSUE TITLE
使用paddleocr 3.0.2测试,会出现Segmentation fault问题

### ISSUE THREAD

**Issue by Miao367147258** [PaddlePaddle/PaddleOCR#15796]
### 🔎 Search before asking

- [x] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [x] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [x] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

使用paddleocr 3.0.2测试,会出现Segmentation fault问题
使用paddleocr 3.0.1测试,则不会出现Segmentation fault问题
换成mobile模型则不会出现Segmentation fault问题
测试使用的电脑内存为16GB,会出现Segmentation fault问题,觉得是因为内存太小引起的,因此换到另外一个80GB内存的电脑上测试,仍然会出现该问题;
电脑没有独立显卡，只有CPU,CPU型号Intel(R) Core(TM) i5-12400

### 🏃‍♂️ Environment (运行环境)

python 3.12+paddleocr 3.0.2+ubuntu 24.04，电脑没有独立显卡，只有CPU,CPU型号Intel(R) Core(TM) i5-12400

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

附件文件:
test-paddleocr-3.0.2.py 为测试用的python脚本文件
语文听写-026.jpg 为测试用的图片文件
requirements-for-paddleocr.txt 为安装的软件包及版本信息
configure-paddleocr 中包含使用miniconda创建测试环境的命令
test-log 为运行log信息,可以看到会出现Segmentation fault错误

[test-paddleocr-3.0.2-20250620.tar.gz](https://github.com/user-attachments/files/20836569/test-paddleocr-3.0.2-20250620.tar.gz)

Segmentation fault信息:
python3 test-paddleocr-3.0.2.py
/media/xxxyyy/miniconda3/envs/env-for-paddleocr-3.0.2/lib/python3.12/site-packages/paddle/utils/cpp_extension/extension_utils.py:711: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Using official model (PP-LCNet_x1_0_doc_ori), the model files will be automatically downloaded and saved in /home/xxxyyy/.paddlex/official_models.
Creating model: ('UVDoc', None)
Using official model (UVDoc), the model files will be automatically downloaded and saved in /home/xxxyyy/.paddlex/official_models.
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Using official model (PP-LCNet_x1_0_textline_ori), the model files will be automatically downloaded and saved in /home/xxxyyy/.paddlex/official_models.
Creating model: ('PP-OCRv5_server_det', None)
Using official model (PP-OCRv5_server_det), the model files will be automatically downloaded and saved in /home/xxxyyy/.paddlex/official_models.
Creating model: ('PP-OCRv5_server_rec', None)
Using official model (PP-OCRv5_server_rec), the model files will be automatically downloaded and saved in /home/xxxyyy/.paddlex/official_models.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun(bool)
1   paddle::framework::NaiveExecutor::RunInterpreterCore(std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
2   paddle::framework::InterpreterCore::Run(std::vector<std::string, std::allocator<std::string > > const&, bool, bool, bool, bool)
3   paddle::framework::PirInterpreter::Run(std::vector<std::string, std::allocator<std::string > > const&, bool, bool, bool, bool)
4   paddle::framework::PirInterpreter::TraceRunImpl()
5   paddle::framework::PirInterpreter::TraceRunInstructionList(std::vector<std::unique_ptr<paddle::framework::InstructionBase, std::default_delete<paddle::framework::InstructionBase> >, std::allocator<std::unique_ptr<paddle::framework::InstructionBase, std::default_delete<paddle::framework::InstructionBase> > > > const&)
6   paddle::framework::PirInterpreter::RunInstructionBase(paddle::framework::InstructionBase*)
7   paddle::framework::PhiKernelInstruction::Run()
8   phi::KernelImpl<void (*)(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, phi::DenseTensor*), &(void phi::ConvKernel<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, phi::DenseTensor*))>::Compute(phi::KernelContext*)
9   void phi::ConvKernelImpl<float, phi::CPUContext>(phi::CPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, int, std::vector<int, std::allocator<int> > const&, std::string const&, phi::DenseTensor*)
10  phi::funcs::Im2ColFunctor<(phi::funcs::ColFormat)0, phi::CPUContext, float>::operator()(phi::CPUContext const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::DenseTensor*, common::DataLayout)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1750421447 (unix time) try "date -d @1750421447" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x725e471f5300) received by PID 3995330 (TID 0x7264625ef740) from PID 1193235200 ***]

Killed

**Comment by Bobholamovic** [comment]
麻烦看看这个issue里的回答是否有帮助～
https://github.com/PaddlePaddle/PaddleOCR/pull/15790

**Comment by Miao367147258** [comment]
看起来现象是一样的,等下一个版本再试试吧,现在先用着之前的版本,多谢回复.

**Comment by Bobholamovic** [comment]
好的，感谢理解

**Comment by esther-huang** [comment]
使用 **paddleocr 3.0.1** (cpu mode), 同样出现了Segmentation fault问题。

## Environment（运行环境）：
Host OS: Linux (Ubuntu 22.04.4 LTS)
Docker Version: 27.1.2
CPU Info：Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz

## 最小可复现问题的Demo：
Terminal 1:
```
docker build -t test_paddlex_serving -f ./Dockerfile.cpu .

docker run -p 9090:8080 test_paddlex_serving
```
Terminal 2:
```
python PaddleOCR_API_test.py
```

[test_paddleocr_3.0.1_20250625.zip](https://github.com/user-attachments/files/20916581/test_paddleocr_3.0.1_20250625.zip)

附件 test_paddleocr_3.0.1_20250625.zip 含：
PaddleOCR_API_test.py：测试用脚本文件
Dockerfile.cpu：用于创建docker image
test_tags.png：测试用图片文件
docker_log.log：Docker log 信息（可以看到Segmentation fault）

**Comment by Bobholamovic** [comment]
> Host OS: Linux (darwin 24.3.0)

请问是darwin还是linux呀？

**Comment by esther-huang** [comment]
> 请问是darwin还是linux呀？

是 Linux (Ubuntu 22.04.4 LTS)，已编辑

**Comment by Bobholamovic** [comment]
好的，请提供一下paddlex版本，以及`PaddleOCR`对象的实例化参数～

**Comment by esther-huang** [comment]
> 好的，请提供一下paddlex版本，以及`PaddleOCR`对象的实例化参数～

paddlex3.0.1
使用了默认的OCR产线配置
```
SubModules:
  TextDetection:
    box_thresh: 0.6
    limit_side_len: 736
    limit_type: min
    max_side_limit: 4000
    model_dir: null
    model_name: PP-OCRv5_server_det
    module_name: text_detection
    thresh: 0.3
    unclip_ratio: 1.5
  TextLineOrientation:
    batch_size: 6
    model_dir: null
    model_name: PP-LCNet_x0_25_textline_ori
    module_name: textline_orientation
  TextRecognition:
    batch_size: 6
    model_dir: null
    model_name: PP-OCRv5_server_rec
    module_name: text_recognition
    score_thresh: 0.0
SubPipelines:
  DocPreprocessor:
    SubModules:
      DocOrientationClassify:
        model_dir: null
        model_name: PP-LCNet_x1_0_doc_ori
        module_name: doc_text_orientation
      DocUnwarping:
        model_dir: null
        model_name: UVDoc
        module_name: image_unwarping
    pipeline_name: doc_preprocessor
    use_doc_orientation_classify: true
    use_doc_unwarping: true
pipeline_name: OCR
text_type: general
use_doc_preprocessor: true
use_textline_orientation: true 
```
