### ISSUE TITLE
east网络验证时耗时太久

### ISSUE THREAD

**Issue by NextGuido** [PaddlePaddle/PaddleOCR#196]
我在运行east网络进行icdar文本检测的时候，验证阶段的一直卡在这个界面，现在都快20分钟了，重新尝试了好多次都是这样，这是为什么啊？
![选区_001](https://user-images.githubusercontent.com/37173179/84473405-95c81100-acbb-11ea-89b1-780208644339.png)

训练的配置文件 `configs/det/det_r50_vd_east.yml` 如下：
```
Global:
  algorithm: EAST
  use_gpu: true
  epoch_num: 100000
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/det_east/
  save_epoch_step: 200
  eval_batch_step: 20
  train_batch_size_per_card: 48
  test_batch_size_per_card: 16
  image_shape: [3, 512, 512]
  reader_yml: ./configs/det/det_east_icdar15_reader.yml
  pretrain_weights: ./pretrain_models/ResNet50_vd_ssld_pretrained/
  save_res_path: ./output/det_east/predicts_east.txt
  checkpoints:
  save_inference_dir:

Architecture:
  function: ppocr.modeling.architectures.det_model,DetModel

Backbone:
  function: ppocr.modeling.backbones.det_resnet_vd,ResNet
  layers: 50

Head:
  function: ppocr.modeling.heads.det_east_head,EASTHead
  model_name: large
  
Loss:
  function: ppocr.modeling.losses.det_east_loss,EASTLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.001
  beta1: 0.9
  beta2: 0.999

PostProcess:
  function: ppocr.postprocess.east_postprocess,EASTPostPocess
  score_thresh: 0.8
  cover_thresh: 0.1
  nms_thresh: 0.2
  
```
