### ISSUE TITLE
内存溢出的问题！

### ISSUE THREAD

**Issue by NextGuido** [PaddlePaddle/PaddleOCR#218]
我在训练文本检测网络DB时候，经常会出现内存溢出的问题，如下：
![aaa](https://user-images.githubusercontent.com/37173179/84774064-df905e80-b00f-11ea-8fb9-84c474045dfa.png)
其中，配置文件`det_r50_vd_db.yml`的内容如下：
```
Global:
  algorithm: DB
  use_gpu: true
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 30
  save_model_dir: ./output/det_db/
  save_epoch_step: 200
  eval_batch_step: 10000
  train_batch_size_per_card: 2
  test_batch_size_per_card: 1
  image_shape: [3, 640, 640]
  reader_yml: ./configs/det/det_db_chinese_reader.yml
  pretrain_weights: ./pretrain_models/ResNet50_vd_ssld_pretrained/
  save_res_path: ./output/det_db/predicts_db.txt
  checkpoints: 
  save_inference_dir:
```
配置文件`det_db_chinese_reader.yml`的内容如下：
```
TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.db_process,DBProcessTrain
  num_workers: 4
  img_set_dir: ""
  label_file_path: /home/aistudio/data/data39969/mtwi_2018_split/train.txt

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: ""
  label_file_path: /home/aistudio/data/data39969/mtwi_2018_split/test.txt
  test_image_shape: [736, 1280]
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  infer_img:
  img_set_dir: ""
  label_file_path: /home/aistudio/data/data39969/icpr_mtwi_task2/test.txt
  test_image_shape: [736, 1280]
  do_eval: True
```
训练数据集来自于[https://tianchi.aliyun.com/competition/entrance/231685/information](url)，手动划分数据，训练集和验证集的划分比例9:1（9043:1005）。我的batch_size从2~16都试过，一直会出现内存溢出的问题，num_workers=1的话，可以训练，但是训练的迭代速度就太慢了。请问，有什么好的解决方法吗？

**Comment by wolfryu** [comment]
#112 
大半个月前就有人开始反应的问题，其结果只能拿来跑icdar2015这个测试数据。

**Comment by NextGuido** [comment]
至今还没有好的解决办法吗？现在根本训练不起来，忧伤

**Comment by SixGodGG** [comment]
我在win下，使用det_mv3_db.yml 预训练模型为：MobileNetV3_large_x0_5_pretrained.tar。
使用自己的数据集，在RTX2080下，图像尺寸归一化到3，640，640  train_batch_size_per_card 可以设为12。

**Comment by NextGuido** [comment]
@SixGodGG 我的是det_r50_vd_db模型，而且是在ubuntu系统下面，win还没有试过

**Comment by SixGodGG** [comment]
那有可能

**Comment by txyugood** [comment]
我也遇到这个问题了。貌似多进程会内存溢出，查了一遍也看不出来什么问题，期待官方吧。我这里有个暂时的解决办法就是把多进程关掉。
1.首先把 configs/det/det_db_icdar15_reader.yml 配置里面的 num_workers设置为1。
2.将ppocr/data/reader_main.py的75行
`return paddle.reader.multiprocess_reader(readers, False)`
修改为
`return function(0)`。
这样就可以正常训练了，感觉速度也没有变慢，好像还快了一点点。。。

**Comment by tink2123** [comment]
请问是否是在训练过程中eval时，遇到的内存溢出呢？可以尝试拉取最新的代码，最新代码中修改了起始eval的轮数，可能会对您有帮助。

**Comment by NextGuido** [comment]
@tink2123 好的，我这边有时间尝试一下，然后再和你反馈，感谢

**Comment by NextGuido** [comment]
@tink2123 我刚才重新跑了一下，还是用之前的数据，大概跑了15个epoch左右，还是会出现这个问题，训练配置如下：
```
Global:
  algorithm: DB
  use_gpu: true
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 30
  save_model_dir: ./output/det_db/
  save_epoch_step: 100
  eval_batch_step: 5000
  train_batch_size_per_card: 14
  test_batch_size_per_card: 14
  image_shape: [3, 640, 640]
  reader_yml: ./configs/det/det_db_chinese_reader.yml
  pretrain_weights: ../../pretrain_models/ResNet50_vd_ssld_pretrained/
  save_res_path: ./output/det_db/predicts_db.txt
  checkpoints: 
  save_inference_dir:
```
