### ISSUE TITLE
finetune训练后，其他字符没了

### ISSUE THREAD

**Issue by ananas-hebo** [PaddlePaddle/PaddleOCR#2440]
意图是想在现有的识别模型上做微调，比例加特殊字体。
使用软件生成了一些“我是谁” 的训练图片：
![42F62EF5-D439-4C28-BF73-DC9676437B64](https://user-images.githubusercontent.com/5362672/114287645-12be4580-9a9b-11eb-9c46-9f44d5b5812d.png)

导出model，使用代码：
`ocr = PaddleOCR(
    ...
    rec_model_dir='../output/rec_chinese_lite_v2.0_model',  //生成的model
    ...    
)
`
发现识别其他文字，结果文字也只剩下“我是谁”：
![image](https://user-images.githubusercontent.com/5362672/114272712-d6162e00-9a49-11eb-8822-32e205d93110.png)

finetune训练时需要使用全量的dataset，从头训练吗？

配置文件：
```
Global:
  use_gpu: false
  epoch_num: 64
  log_smooth_window: 20
  print_batch_step: 9
  save_model_dir: ./output/rec_chinese_lite_v2.0
  save_epoch_step: 20
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 9, 2000]
  # if pretrained_model is saved in static mode, load_static_weights must set to True
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/ch_ppocr_mobile_v2.0_rec_pre/best_accuracy  
  checkpoints: 
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: False


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data_demo/
    label_file_list: ["./train_data_demo/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug: 
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 16
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data_demo/
    label_file_list: ["./train_data_demo/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 8
```
