### ISSUE TITLE
使用paddle serving 多线程访问服务端失败

### ISSUE THREAD

**Issue by xealml** [PaddlePaddle/PaddleOCR#2549]
1. 使用该教程来搭建服务https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/deploy/pdserving/README_CN.md
2. 使用以下的脚本来测试服务器性能。
```
import numpy as np
import requests
import json
import base64
import os
import time
import queue
from concurrent.futures import ThreadPoolExecutor


class BoundThreadPoolExecutor(ThreadPoolExecutor):
    def __init__(self, *args, **kwargs):
        super(BoundThreadPoolExecutor, self).__init__(*args, **kwargs)
        self._work_queue = queue.Queue(2)


worker = BoundThreadPoolExecutor()
def cv2_to_base64(image):
    return base64.b64encode(image).decode('utf8')

def handle(data):
    start = time.time()
    r = requests.post(url=url, data=json.dumps(data))
    print(r.json())
    print('-' * 20, time.time() - start)

# url = "http://127.0.0.1:9999/ocr/prediction"
url = "http://127.0.0.1:9999/ocr/prediction"
test_img_dir = "../doc/imgs/"
all_start = time.time()
for idx, img_file in enumerate(os.listdir(test_img_dir)):
    with open(os.path.join(test_img_dir, img_file), 'rb') as file:
        image_data1 = file.read()

    image = cv2_to_base64(image_data1)

    for i in range(1):
        data = {"key": ["image"], "value": [image]}
        # handle(data)                          # route1
        worker.submit(handle, data)   # route2

test_img_dir = "../doc/imgs/"
print("==> total number of test imgs: ", len(os.listdir(test_img_dir)))
print('***', time.time() - all_start)
```
3. 现象
1. 以上例子，单线程访问，即不注释# route1那，注释#route2行，访问时间为32s
2. 多线程访问，以上的例子，整体跑完需要41s左右，且会在最后一个case时产生错误
3. paddle serving 服务端会报这个错误
```
W0419 03:18:02.994657 30772 predictor.hpp:129] inference call failed, message: [E104]1/1 channels failed, fail_limit=1 [C0][E1014]Got EOF of fd=59 SocketId=1@127.0.0.1:12004@52056 [R1][E104]Fail to read from fd=64 SocketId=8589934594@127.0.0.1:12004@52064: Connection reset by peer [R2][E104]Fail to read from fd=59 SocketId=8589934696@127.0.0.1:12004@52066: Connection reset by peer
```
4.        2中的请求端会报这个错误
```
{'err_no': 5, 'err_msg': '(log_id=393) [det|1] Failed to predict, please check if PaddleServingService is working properly.', 'key': [], 'value': []}
```

4. serving端config.yml
```
ort设置为http_port+1
rpc_port: 18090

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 9999

#worker_num, 最大并发数。当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
##当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 20

#build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: True

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: True

    #重试次数
    retry: 1

    #使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
    use_profile: False

    tracer:
        interval_s: 10
op:
    det:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 20

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:
            #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
            client_type: brpc

            #det模型路径
            model_config: /home/nlp-paddle-ocr/PaddleOCR/deploy/pdserving/ppocr_det_server_2.0_serving/ #ocr_det_model

            #Fetch结果列表，以client_config中fetch_var的alias_name为准
            fetch_list: ["save_infer_model/scale_0.tmp_1"]

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "1"

            ir_optim: True
            # 批量查询Serving的数量, 默认1。batch_size>1要设置auto_batching_timeout，否则不足batch_size时会阻塞
            batch_size: 8

            # 批量查询超时，与batch_size配合使用
            auto_batching_timeout: 20000

    rec:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 20

        #超时时间, 单位ms
        timeout: -1

        #Serving交互重试次数，默认不重试
        retry: 1

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:

            #client类型，包括brpc, grpc和local_predictor。local_predictor不启动Serving服务，进程内预测
            client_type: brpc

            #rec模型路径
            model_config: /home/nlp-paddle-ocr/PaddleOCR/deploy/pdserving/ppocr_rec_server_2.0_serving/ #ocr_rec_model

            #Fetch结果列表，以client_config中fetch_var的alias_name为准
            fetch_list: ["save_infer_model/scale_0.tmp_1"] #["ctc_greedy_decoder_0.tmp_0", "softmax_0.tmp_0"]

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "1"

            ir_optim: True

            # 批量查询Serving的数量, 默认1。batch_size>1要设置auto_batching_timeout，否则不足batch_size时会阻塞
            batch_size: 8

            # 批量查询超时，与batch_size配合使用
            auto_batching_timeout: 20000
```
