### ISSUE TITLE
DetResizeForTest设置对训练结果有严重影响

### ISSUE THREAD

**Issue by ronaldpan** [PaddlePaddle/PaddleOCR#2684]
我把DetResizeForTest参数设置为：   

```
   - DetResizeForTest:
#           image_shape: [736, 1280]
            limit_side_len: 2048
            limit_type: max
```

训练时 precision和recall都很低。

```
   - DetResizeForTest:
#           image_shape: [736, 1280]
```

训练时 precision和recall都很高。
请问这是为什么？
