### ISSUE TITLE
对中英文通用OCR模型(server)finetune符号集

### ISSUE THREAD

**Issue by HaodiFan** [PaddlePaddle/PaddleOCR#2856]
Q: 我合成了一些符号的数据集（包括原先ppocr_keys_v1.txt 之外的符号）但是训练的时候我配置文件里设置的是ppocr_keys_v1.txt作为字典。理论上说finetune的时候应该会将字典外的字符编码失败所以应该正常训练是不会有问题的。训练完后用于原先的场景所有原本识别为**中文**的字符都变成了**符号**。（没有保持原先i字典里字符的权重参数）finetune训练集大小：29w。
yml as follow:
```
Global:
  use_gpu: true
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/ic15_aug/ 
  save_epoch_step: 3
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: ch_ppocr_server_v2.0_rec_pre/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: /PaddleOCR/ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_ic15_2.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: dataset/special_label_dataset/rec/train
    label_file_list: ["dataset/special_label_dataset/rec/rec_gt_train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /special_label_dataset/rec/eval
    label_file_list: ["/special_label_dataset/rec/rec_gt_eval.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4
    use_shared_memory: False
```
