### ISSUE TITLE
Memory Usage Issue

### ISSUE THREAD

**Issue by mohamadmansourX** [PaddlePaddle/PaddleOCR#4136]
While working with SAST detection, I'm facing a memory issue after running the model for few iterations (100ks iteration).

I'm working with:
- **GPU**: GeForce GTX 1060 6GB
- **RAM**: 16 GB
- **CPU(s)**:
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
NUMA node(s):                    1
Model name:                      Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
NUMA node0 CPU(s):               0-15

I have around 317758 images for training and 9828 for testing:

> root INFO: train dataloader has 158879 iters
> root INFO: valid dataloader has 9828 iters

After running the model for few iterations, the RAMs usage keeps incrementing with time until the memory is full as shown in the graph below:

*Note: At each interval for each evaluation, the value of the Used/Available RAM's graph has a sharp increment/decrement*

[Full logs](https://pastebin.com/1YPKv5Qj)

![image](https://user-images.githubusercontent.com/66031317/134319781-a7ee1cf6-a1a1-465f-bcca-1b336bd015f3.png)

### Config:
```yaml
Global:
    debug: false
    use_gpu: true
    epoch_num: 700
    distributed: false
    use_visualdl: false
    eval_batch_step:
    - 0
    - 10000
    print_batch_step: 100
    log_smooth_window: 20
    cal_metric_during_train: false
    ...
Loss:
    name: SASTLoss
Architecture:
    Head:
      name: SASTHead
    Neck:
      name: SASTFPN
      with_cab: true
    Backbone:
      name: ResNet_SAST
      layers: 50
    Transform:
    algorithm: SAST
    model_type: det
Metric:
    name: DetMetric
    main_indicator: hmean
Optimizer:
    lr:
      name: Cosine
      warmup_epoch: 0
      learning_rate: 0.001
    name: Adam
    beta1: 0.9
    beta2: 0.999
    regularizer:
      name: L2
      factor: 0
PostProcess:
    name: SASTPostProcess
    nms_thresh: 0.2
    expand_scale: 1
    score_thresh: 0.5
    sample_pts_num: 2
    shrink_ratio_of_width: 0.3

Eval:
    loader:
      shuffle: false
      drop_last: false
      num_workers: 0
      use_shared_memory: false
      batch_size_per_card: 1
    dataset:
      ...
Train:
    loader:
      shuffle: true
      drop_last: false
      num_workers: 0
      use_shared_memory: false
      batch_size_per_card: 2
    dataset:
      ...

```

Using EAST or DB with R50 backbone works normally and had no issue with memory.
