### ISSUE TITLE
PaddleOCR 模型转换问题

### ISSUE THREAD

**Issue by chccc1994** [PaddlePaddle/PaddleOCR#4795]
问题：
1.  在PaddleOCR 2.3版本上训练的 文本检测或者文本识别模型，动态图怎么转换了静态图？[**export_model.py**](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/tools/export_model.py)是导出静态图吗？（还是动态图的固化）
2.  在PaddleOCR develop版本下训练ICDAR2015 ,训练epoch=60 就中断，没有报错。

配置文件如下：
```yml
Global:
  algorithm: DB
  use_gpu: true
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 2
  save_model_dir: ./output/det_db_icdar15_reader/
  save_epoch_step: 3
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 2000]
  train_batch_size_per_card: 16
  test_batch_size_per_card: 16
  image_shape: [3, 640, 640]
  reader_yml: ./configs/det/det_db_icdar15_reader.yml
  pretrain_weights: ./pretrain_models/MobileNetV3_large_x0_5_pretrained/
  checkpoints:
  save_res_path: ./output/det_db/predicts_db.txt
  save_inference_dir:
  
Architecture:
  function: ppocr.modeling.architectures.det_model,DetModel

Backbone:
  function: ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3
  scale: 0.5
  model_name: large
  disable_se: true

Head:
  function: ppocr.modeling.heads.det_db_head,DBHead
  model_name: large
  k: 50
  inner_channels: 96
  out_channels: 2

Loss:
  function: ppocr.modeling.losses.det_db_loss,DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.001
  beta1: 0.9
  beta2: 0.999
  decay:                                                                                                                         
    function: cosine_decay_warmup
    step_each_epoch: 16                                                                                                         
    total_epoch: 1200

PostProcess:
  function: ppocr.postprocess.db_postprocess,DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

```

```bash
TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.db_process,DBProcessTrain
  num_workers: 8
  img_set_dir: E:/Paddle/datasets/ICDAR2015/Text_Localization/
  label_file_path: E:/Paddle/datasets/ICDAR2015/Text_Localization/train_icdar2015_label.txt

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: E:/Paddle/datasets/ICDAR2015/Text_Localization/
  label_file_path: E:/Paddle/datasets/ICDAR2015/Text_Localization/test_icdar2015_label.txt
  test_image_shape: [736, 1280]
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  infer_img:
  img_set_dir: E:/Paddle/datasets/ICDAR2015/Text_Localization/
  label_file_path: E:/Paddle/datasets/ICDAR2015/Text_Localization/test_icdar2015_label.txt
  test_image_shape: [736, 1280]
  do_eval: True

```
