### ISSUE TITLE
文本识别训练自己的数据GPU占用非常低

### ISSUE THREAD

**Issue by xinyujituan** [PaddlePaddle/PaddleOCR#5305]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：WINDOWS10
- 版本号/Version：Paddle：  PaddleOCR： 2.2 问题相关组件/Related components：cuda:10.2,11.1都测试过 一样占用都很低
- 运行指令/Command Code：-c configs/my.yml
- 完整报错/Complete Error Message：GPU占用低 批次改大会出现这样的占用结果
![image](https://user-images.githubusercontent.com/53806323/150277182-266aefa3-b003-416c-818e-085c9a5fe16a.png)
改小点的话会稳定在25%左右的占用，样本放在了固态硬盘。
下面是我的my.yml配置

```
Global:
  character_type: ch
  use_gpu: true
  epoch_num: 50000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_chinese_lite_v2.0
  save_epoch_step: 50
  # evaluation is run every 5000 iterations after the 4000th iteration
#  eval_batch_step: 50
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
#  pretrained_model: pretrain_models/ch_ppocr_mobile_v1.1_det_train/best_accuracy.pdparams
  pretrained_model: output/rec_chinese_lite_v2.0/best_accuracy.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: False
#  infer_img: doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: train_data/labels.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: True
  save_res_path: ./output/rec/predicts_chinese_lite_v2.0.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
#    learning_rate: 0.01
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0.00001

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list: ["./train_data/train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data
    label_file_list: ["./train_data/test.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 16
    num_workers: 4
```
