### ISSUE TITLE
在ICDAR2015上测试，训练准确率高，val特别低

### ISSUE THREAD

**Issue by morestart** [PaddlePaddle/PaddleOCR#5443]
train的准确率很高，但是val的非常低，数据集是ICDAR2015

训练命令 
`python3 -m paddle.distributed.launch --log_dir=./debug/ --gpus '0'  tools/train.py -c /home/cat/Desktop/PaddleOCR-release-2.4/configs/rec/rec_icdar15_train.yml
`

```
[2022/02/11 09:23:15] root INFO: epoch: [600/600], iter: 10199, lr: 0.000500, loss: 0.083509, acc: 0.984371, norm_edit_dis: 0.994565, reader_cost: 0.00006 s, batch_cost: 0.05497 s, samples: 2304, ips: 4191.43876
[2022/02/11 09:23:16] root INFO: save model in ./output/rec/ic15/latest
[2022/02/11 09:23:16] root INFO: save model in ./output/rec/ic15/iter_epoch_600
[2022/02/11 09:23:16] root INFO: best metric, acc: 0.013024595743079717, norm_edit_dis: 0.11359001644052125, fps: 8439.407288056133, best_epoch: 589
INFO 2022-02-11 09:23:19,664 launch.py:311] Local processes completed.
```

**Comment by andyjpaddle** [comment]
有对配置文件做过什么修改吗？看样子是严重过拟合了

**Comment by morestart** [comment]
```
Global:
  use_gpu: true
  epoch_num: 600
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/ic15/
  save_epoch_step: 3
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir: ./
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: /home/cat/Desktop/PO/dict.txt
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_ic15.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/cat/Desktop/PO/icdar2015/recognition/train
    label_file_list: ["/home/cat/Desktop/PO/train.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 8
    use_shared_memory: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/cat/Desktop/PO/icdar2015/recognition/test
    label_file_list: ["/home/cat/Desktop/PO/val.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4
    use_shared_memory: False

```
