### ISSUE TITLE
使用自己的字典训练模型出错

### ISSUE THREAD

**Issue by LopSdir** [PaddlePaddle/PaddleOCR#5542]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

程序在aistudio上面的至尊版，使用的paddleocr 版本是 release2.4最新版本，配置文件如下

```yml
Global:
  use_gpu: True
  epoch_num: 72
  log_smooth_window: 20
  print_batch_step: 5
  save_model_dir: ./output/rec/srn_new
  save_epoch_step: 15
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 1000]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg
  max_text_length: 25
  num_heads: 8
  infer_mode: False
  use_space_char: False
  character_dict_path: ppocr/utils/all_number_dict.txt
  character_type: ch
  save_res_path: ./output/rec/predicts_srn.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    learning_rate: 0.0001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform:
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512

Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/work/scripts/generate/train/
    label_file_list: ["/home/aistudio/work/scripts/generate/train_label.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: False
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/aistudio/work/scripts/generate/test/
    label_file_list: ["/home/aistudio/work/scripts/generate/test_label.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] 
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 128
    num_workers: 8
```

生成预测模型脚本如下
```bash
config=configs/rec/rec_srn.yml
checkpoints=/home/aistudio/work/PaddleOCR/output/rec/srn_new/best_accuracy
save_infer=/home/aistudio/work/trian_models/rec/srn
python3 tools/export_model.py -c $config -o Global.checkpoints=$checkpoints Global.save_inference_dir=$save_infer
```

进行预测如下
```bash
img_path=/home/aistudio/work/data/crop/1000050025512280.jpg
# /home/aistudio/work/trian_models/rec/srn/inference
model_path=/home/aistudio/work/trian_models/rec/srn/inference
dict=/home/aistudio/work/PaddleOCR/ppocr/utils/all_number_dict.txt
python3 tools/infer/predict_rec.py --image_dir=$img_path --rec_model_dir=$model_path --rec_image_shape="3, 32, 320" --rec_char_dict_path=$dict --rec_char_type="ch"
```

有两个问题
1. 在我训练模型的时候，训练acc一直在涨（80%），但是验证集上面的acc在35%左右就不涨了
2. 我用生成的预测模型进行预测的时候，回报如下错误
```text
aistudio@jupyter-115314-3498575:~/work/PaddleOCR$ bash infer.sh 
[[[2.37767249e-02 1.41873707e-05 6.65980633e-06 ... 5.70487053e-08
   1.74457355e-07 3.95184674e-04]
  [5.59747756e-01 1.75926194e-04 2.84425896e-05 ... 5.95777783e-09
   9.43004874e-09 2.59762892e-04]
  [8.84199798e-01 6.82148384e-05 7.14277849e-06 ... 2.03647876e-09
   2.50858867e-09 6.48242771e-04]
  ...
  [9.93470788e-01 2.02495247e-08 3.58165808e-09 ... 1.07277928e-11
   6.86260467e-12 1.68920611e-04]
  [9.97284174e-01 6.28113810e-08 3.26510508e-09 ... 1.32932129e-11
   1.27051746e-11 1.79763127e-04]
  [9.84237134e-01 3.87792397e-07 1.00145066e-07 ... 2.14468623e-10
   2.19318133e-10 1.29197229e-04]]]
[2022/02/22 12:52:07] root INFO: Traceback (most recent call last):
  File "tools/infer/predict_rec.py", line 401, in main
    rec_res, _ = text_recognizer(img_list)
  File "tools/infer/predict_rec.py", line 371, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/aistudio/work/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 96, in __call__
    text = self.decode(preds_idx, preds_prob, is_remove_duplicate=True)
  File "/home/aistudio/work/PaddleOCR/ppocr/postprocess/rec_postprocess.py", line 68, in decode
    idx])])
IndexError: list index out of range

[2022/02/22 12:52:07] root INFO: list index out of range
```
