### ISSUE TITLE
SRN修改配置文件中img_shape后，生成推理模型，使用predict_rec报错

### ISSUE THREAD

**Issue by Babysun-ljh** [PaddlePaddle/PaddleOCR#5615]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem
- 系统环境/System Environment：python3.6
- 版本号/Version：Paddle：2.4-release  
- 配置文件如下：
```yml
Global:
  use_gpu: True
  epoch_num: 300
  log_smooth_window: 20
  print_batch_step: 40
  save_model_dir: /data/qiuchaiya/git_latest_paddle/paddleocr_2_4/output/rec/srn_news
  save_epoch_step: 10

  eval_batch_step: [70000, 2000]

  cal_metric_during_train: True
  pretrained_model: /data/qiuchaiya/git_latest_paddle/rec_r50_vd_srn_train/best_accuracy

  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words/ch/word_1.jpg

  character_dict_path: /data/qiuchaiya/git_latest_paddle/paddleocr_2_4/ppocr/utils/en_dict_keys.txt
  character_type: EN
  max_text_length: 25
  num_heads: 8
  infer_mode: False
  use_space_char: False
  save_res_path: /data/qiuchaiya/git_latest_paddle/paddleocr_2_4/output/rec/predicts_srn.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10.0
  lr:
    learning_rate: 0.0001

Architecture:
  model_type: rec
  algorithm: SRN
  in_channels: 1
  Transform:
  Backbone:
    name: ResNetFPN
  Head:
    name: SRNHead
    max_text_length: 25
    num_heads: 8
    num_encoder_TUs: 2
    num_decoder_TUs: 4
    hidden_dims: 512

Loss:
  name: SRNLoss

PostProcess:
  name: SRNLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /data/qiuchaiya/paddleocr/tools/train_data/train/train

    ratio_list: [1.0, 0.5, 0.5]
    label_file_list: ["/data/qiuchaiya/paddleocr/tools/train_data/train_list.txt", "/data/qiuchaiya/paddleocr/tools/train_data/test_list.txt", "/data/qiuchaiya/wedjat4py/torch_ocr/labeled.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - RecAug:
          aug_prob: 0.2
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] # dataloader will return list in this order
  loader:
    shuffle: False
    batch_size_per_card: 256
    drop_last: False
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /data/qiuchaiya/paddleocr/tools/train_data/train/train
    label_file_list: [ "/data/qiuchaiya/paddleocr/tools/train_data/test_list.txt" ]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - SRNLabelEncode: # Class handling label
      - SRNRecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image',
                      'label',
                      'length',
                      'encoder_word_pos',
                      'gsrm_word_pos',
                      'gsrm_slf_attn_bias1',
                      'gsrm_slf_attn_bias2'] 
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 2
```
运行
```bash
 python tools/export_model.py -c configs/rec_pda/rec_r50_fpn_srn_finetune.yml -o Global.pretrained_model=output/rec/srn_news/best_accuracy Global.save_inference_dir=output/inference/rec_srn_infer

python tools/infer/predict_rec.py --image_dir="/data/qiuchaiya/0_0f0bc619-e933-4ece-abab-8781e581ad2f.png" --rec_model_dir=output/inference/rec_srn_infer --rec_image_shape="3, 32, 320" --rec_char_dict_path=/data/qiuchaiya/git_latest_paddle/paddleocr_2_4/ppocr/utils/en_dict_keys.txt --rec_algorithm="SRN"
```
- 完整报错/Complete Error Message：
```bash
InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 512, 4, 40], X's size = 81920, 'shape' is [-1, 512, 256], known capacity of 'shape' is -131072.
      [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-81920.] (at /paddle/paddle/fluid/operators/reshape_op.cc:210)
      [operator < reshape2 > error]
```
