### ISSUE TITLE
rec_r50fpn_vd_none_srn.tar 对应yml配置能提供一个？

### ISSUE THREAD

**Issue by HuangKBAaron** [PaddlePaddle/PaddleOCR#585]
用rec_r34_vd_none_none_ctc.yml改？我有三个地方不确定参数。
这是r34的。应该改成什么？
```
Head:
  function: ppocr.modeling.heads.rec_ctc_head,CTCPredict
  encoder_type: rnn
  SeqRNN:
    hidden_size: 256
    
Loss:
  function: ppocr.modeling.losses.rec_ctc_loss,CTCLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.001
  beta1: 0.9
  beta2: 0.999

```
