### ISSUE TITLE
PP-OCRV3识别模型训练收敛问题

### ISSUE THREAD

**Issue by ziyaxuanyi** [PaddlePaddle/PaddleOCR#6355]
同样的训练数据集，V2版本模型训练精度能收敛到0.89左右，而V3版本的模型精度只能收敛到0.80左右。

使用的是默认的ch_PP-OCRv3_rec_distillation.yml配置，由于显卡显存不够，只修改了batch size从128减小到64。
请问是什么原因了，需要做哪些修改？

怀疑是GTC训练策略有影响，现在只想训练不带GTC只用CTC的PP-OCRV3识别模型，修改配置文件会报错，看报错信息是训练V3必须带GTC的部分loss的内容。请问怎样修改配置才能训练不带GTC的识别模型，或者给出只用CTC训练的训练配置文件？

**Comment by tink2123** [comment]
如果想去掉GTC，可以在配置文件中，修改Architecture的部分：

```
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Neck:
    name: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: False
  Head:
    name: CTCHead
    fc_decay: 0.00001
```

蒸馏 loss 参考 https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/configs/rec/ch_PP-OCRv2/ch_PP-OCRv2_rec_distillation.yml 配置
