### ISSUE TITLE
How to add multiple training and evaluation datasets for svtr large?

### ISSUE THREAD

**Issue by mobassir94** [PaddlePaddle/PaddleOCR#6568]
hi,
thank you for sharing such awesome work with us.
i tried to train svtr base model,i see we can add one simpledataset for training and evaluation like this : 

```
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/apsisdev/mobassir/bnsynthtiger/PaddleOCR/train_data/
    label_file_list : ['/home/apsisdev/mobassir/bnsynthtiger/PaddleOCR/train_data/gt.txt']
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          character_dict_path:
          image_shape: [3, 64, 256]
          padding: False
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 50
    drop_last: True
    num_workers: 0
```
however there are few more folders where i have more training images and corresponding gt.txt labels.
without merging all images in same folder and all gt.txt in single txt file i would like to know if there is any way to load multiple datasets located in different folders or not?
this was my first question,my second question is,i want to train svtr large from scratch,documentation shows instruction for svtr tiny and also not finding yaml file for training svtr large variant? how can i train svtr large on non latin language? thanks in advance
