### ISSUE TITLE
kie_unet_sdmgr.yml中修改了character_dict_path后，如何修改对应的SDMGRHead里的num_chars

### ISSUE THREAD

**Issue by happybuby** [PaddlePaddle/PaddleOCR#6828]
kie_unet_sdmgr.yml中修改了character_dict_path后，如何修改对应的SDMGRHead里的num_chars,如果num_chars和字典的实际数据不一致，训练时会报错，请问怎样进行修改

**Comment by trucdtt** [comment]
I tried to train the KIE model with custom dataset. So, I changed *num_chars* and *num_classes* in ppocr/modeling/heads/kie_sdmgr_head.py when I modified the dictionary. You can try it with your dictionary.

**Comment by happybuby** [comment]
@trucdtt thanks very much ！but when I change the dict or class_list,I will have to change the source code, it is trouble. Is there a way to change the num_chars and num_classes by config yml file?

**Comment by littletomatodonkey** [comment]
hi, you can define the arch as follows:

```yaml
Architecture:
  model_type: kie
  algorithm: SDMGR
  Transform:
  Backbone:
    name: Kie_backbone
  Head:
    name: SDMGRHead
    num_chars: 92 # you can change as your char num
```
