### ISSUE TITLE
config中的algorithm参数

### ISSUE THREAD

**Issue by yyr6661** [PaddlePaddle/PaddleOCR#79]
在学习过程中，我注意到train.py中判断了一下算法参数algorithm是否在已有范围内，之后就找不到哪里使用了这个参数
我想知道代码是怎么实现选择不同的算法的，求大佬们指点

**Comment by LDOUBLEV** [comment]
选择不同的算法是在yml配置文件中定义好的，比如det_mv3_db.yml

yml文件里定义好了要加载的算法模型，和backbone head等
```
Architecture:
  function: ppocr.modeling.architectures.det_model,DetModel

Backbone:
  function: ppocr.modeling.backbones.det_mobilenet_v3,MobileNetV3
  scale: 0.5
  model_name: large

Head:
  function: ppocr.modeling.heads.det_db_head,DBHead
  model_name: large
  k: 50
  inner_channels: 96
  out_channels: 2
```
