### ISSUE TITLE
怎么设置学习率下降的速度

### ISSUE THREAD

**Issue by nistarlwc** [PaddlePaddle/PaddleOCR#7927]
```
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 10
  regularizer:
    name: L2
    factor: 3.0e-05
```

学习率下降中的learning_rate是最大值，要是想快速下降少训练几轮循环，应该怎么设置呢
