### ISSUE TITLE
增加数据增强 训练耗时增加过多

### ISSUE THREAD

**Issue by guishilike** [PaddlePaddle/PaddleOCR#8182]
- 系统环境/System Environment：Ubuntu
- 版本号/Version：PaddleOCR：2.6 问题相关组件/Related components： Det
- 配置文件：ch_PP-OCRv3_det_student.yml

添加数据增强MultiplyHueAndSaturation后，训练耗时增加特别多

添加后
```
transforms:
  - DecodeImage:
      img_mode: BGR
      channel_first: false
  - DetLabelEncode: null
  - IaaAugment:
      augmenter_args:
        - { 'type': Fliplr, 'args': { 'p': 0 } }
        - { 'type': Affine, 'args': { 'rotate': [ -10, 10 ] } }
        - { 'type': Resize, 'args': { 'size': [ 0.5, 3 ] } }
        - { 'type': MultiplyHueAndSaturation, 'args': { 'mul_hue': [ 0.9, 1.1 ], 'mul_saturation': [ 0.9, 1.1 ] } }
```
![image](https://user-images.githubusercontent.com/51023060/199378176-8e0d382d-3903-441e-9672-5375aac7584f.png)

添加前
![image](https://user-images.githubusercontent.com/51023060/199378805-17d0428c-8fdc-4703-9bad-7ec7e291f565.png)
