### ISSUE TITLE
知识蒸馏模型的teacher模型的预训练参数能不能单独拿出来训练呢？

### ISSUE THREAD

**Issue by OpenOneV** [PaddlePaddle/PaddleOCR#8186]
不知不觉问了四个问题。麻烦万忙中解答了~

1. 从预训练模型pdparams中单独拿出来教师模型可以吗？

2. 如果不方便单独拿出来的话，可不可以通过设置Loss和Architecture中的freeze_params让教师模型单独更新参数而学生模型不参与参数更新呢？
2.1. 最好能关闭学生的前馈，或者让学生不参与最终的Loss计算。不然我只要训练教师模型的话，学生的Loss为什么要算教师头上？这种应该怎么配置Loss和Architecture啊？

3. 请问在yml配置中设置的不同的loss如：
``` yaml
Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationDilaDBLoss:
      weight: 1.0
      model_name_pairs:
      - ["Student", "Teacher"]
      - ["Student2", "Teacher"]
      key: maps
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
  - DistillationDMLLoss:
      model_name_pairs:
      - ["Student", "Student2"]
      maps_name: "thrink_maps"
      weight: 1.0
      # model_name_pairs: ["Student", "Student2"]
      key: maps
  - DistillationDBLoss:
      weight: 1.0
      model_name_list: ["Student", "Student2"]
      balance_loss: true
      main_loss_type: DiceLoss
      alpha: 5
      beta: 10
      ohem_ratio: 3
```
这三种loss是最终相加起来的吗？然后交给Optimizer来更新参数吗？

4. 再问一个：PostProcess是在Loss和Opt之间，还是和Opt没有关系啊？
