### ISSUE TITLE
用PP-OCRv3训练弯曲中文和数字文本的识别，可以添加STN吗？如何添加？

### ISSUE THREAD

**Issue by phb-shiyige-fw** [PaddlePaddle/PaddleOCR#8406]
如题，我看到关于参数配置文件里，ch_PP-OCRv3_rec.yml文件里transforms处写了支持TPS，请问支持STN处理吗？如果支持应该怎么添加相关的参数配置呢？
![image](https://user-images.githubusercontent.com/94897119/203198148-ebe7e80b-289e-4e62-b581-676c7bbfb138.png)

**Comment by phb-shiyige-fw** [comment]
@tink2123 方便回答一下吗 谢谢

**Comment by tink2123** [comment]
参考如下配置修改Transform字段即可添加STN模块：
```
  Transform:
    name: STN_ON
    tps_inputsize: [32, 64]
    tps_outputsize: [32, 100]
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
```
