### ISSUE TITLE
Error Training with rec_r45_abinet.yml

### ISSUE THREAD

**Issue by yong-asial** [PaddlePaddle/PaddleOCR#8549]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：Docker (on Ubuntu 18)
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：release/2.6
- 运行指令/Command Code： N/A
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 183, in main
    amp_level, amp_custom_black_list)
  File "/app/tools/program.py", line 295, in train
    loss = loss_class(preds, batch)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/app/ppocr/losses/rec_ce_loss.py", line 36, in forward
    loss[name + '_loss'] = self.loss_func(flt_logtis, flt_tgt)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/loss.py", line 406, in forward
    name=self.name)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/loss.py", line 1676, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:3744 != labels_dims[i]:21744.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:163)
  [operator < softmax_with_cross_entropy > error]
```

I tried to train with ABInet (rec_r45_abinet.yml) but i got above or similar error. When i tried changing the batch size (or image size), it will display different error but still something with dimension mismatch.

Do you have any guidelines to train with this algorithm (ABInet)? I got the same error as well with VisionLan. I tried with both SimpleDataset and LMDBDataset but neither of them work.

Note: The same dataset, i got it successful training with CRNN and SVTR.

**Comment by andyjpaddle** [comment]
did you modify the default config? or can you provide your config and describe what you modify

**Comment by yong-asial** [comment]
@andyjpaddle i didn't modify the default config but i used my own dataset.

**Comment by andyjpaddle** [comment]
did you modify the default dict? or could you provide your train config?

**Comment by yong-asial** [comment]
@andyjpaddle 

Sure, this is the configuration. You can ignore the training/evaluation dataset (since it is just for testing purpose).

```
Global:
  use_gpu: True
  epoch_num: 10
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./output/rec/r45_abinet/
  save_epoch_step: 1
  eval_batch_step: [0, 2000] 
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: ppocr/utils/dict/oscar_japan.txt
  max_text_length: 150
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_abinet.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.99
  clip_norm: 20.0
  lr:
    name: Piecewise
    decay_epochs: [6]
    values: [0.0001, 0.00001] 
  regularizer:
    name: 'L2'
    factor: 0.

Architecture:
  model_type: rec
  algorithm: ABINet
  in_channels: 3
  Transform:
  Backbone:
    name: ResNet45
  Head:
    name: ABINetHead
    use_lang: True
    iter_size: 3
    

Loss:
  name: CELoss
  ignore_index: &ignore_index 4500

PostProcess:
  name: ABINetLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: evaluation
    label_file_list: 
      - evaluation/japanese-single-line-barna-modified-resized.txt
    ratio_list: 
      - 1.0
    transforms:
      - DecodeImage:
          img_mode: RGB
          channel_first: False
      - ABINetRecAug:
      - ABINetLabelEncode:
          ignore_index: *ignore_index
      - ABINetRecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: True
    batch_size_per_card: 48 
    drop_last: True
    num_workers: 2
    use_shared_memory: True

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: evaluation
    label_file_list: 
      - evaluation/japanese-single-line-barna-modified-resized.txt
    ratio_list: 
      - 1.0
    transforms:
      - DecodeImage:
          img_mode: RGB
          channel_first: False
      - ABINetLabelEncode:
          ignore_index: *ignore_index
      - ABINetRecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 12
    num_workers: 2
    use_shared_memory: True
```

And here is the dictionary 
[oscar_japan.txt](https://github.com/PaddlePaddle/PaddleOCR/files/10163284/oscar_japan.txt)
It has 4400 characters in total.

**Comment by Topdu** [comment]
ABINet will resize the image to 32*128 when training, the most appropriate max_text_length should be 25. If the max_text_length is changed, it is recommended to change the resize parameter (ABINetRecResizeImg) at the same time.

**Comment by yong-asial** [comment]
Thank you for the answer @andyjpaddle @Topdu 

I added the `max_length` to the Head but still got error with the dimension mismatch.

```
Global:
  use_gpu: True
  epoch_num: 10
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./output/rec/r45_abinet/
  save_epoch_step: 20
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: ppocr/utils/dict/oscar_japan.txt
  max_text_length: &max_text_length 150
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_abinet.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.99
  clip_norm: 20.0
  lr:
    name: Piecewise
    decay_epochs: [6]
    values: [0.0001, 0.00001] 
  regularizer:
    name: 'L2'
    factor: 0.

Architecture:
  model_type: rec
  algorithm: ABINet
  in_channels: 3
  Transform:
  Backbone:
    name: ResNet45
  Head:
    name: ABINetHead
    use_lang: True
    iter_size: 3
    max_length: *max_text_length

Loss:
  name: CELoss
  ignore_index: &ignore_index 4440 # Must be greater than the number of character classes

PostProcess:
  name: ABINetLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    ...
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - ABINetRecAug:
      - ABINetLabelEncode: # Class handling label
          ignore_index: *ignore_index
      - ABINetRecResizeImg:
          image_shape: [3, 32, 768]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 24
    drop_last: True
    num_workers: 2

Eval:
  dataset:
    ...
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - ABINetLabelEncode: # Class handling label
          ignore_index: *ignore_index
      - ABINetRecResizeImg:
          image_shape: [3, 32, 768]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 1
    num_workers: 2
    use_shared_memory: False

```

Here is the error
```
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1536, 24, 512] and the shape of Y = [256, 1, 512]. Received [1536] in X is not equal to [256] in Y at i:0.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error
```

If i changed batch size to 12, the error is as following
```
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1536, 12, 512] and the shape of Y = [256, 1, 512]. Received [1536] in X is not equal to [256] in Y at i:0.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error
```

Similarly, If i changed `image_shape` to something else, it will output different error but still something with mismatch dimension.

Are there any hard requirement for the dataset? like the training dataset has to be 32*128? 

If possible, could you send me the sample of training dataset (either in SimpleDataset or LMDBDataset that is working?

Thank you.
