### ISSUE TITLE
Tesla T4 训练文字检测任务 GPU大部分处于0

### ISSUE THREAD

**Issue by LUOQING1994** [PaddlePaddle/PaddleOCR#8983]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：ubentu 18.04 \ cuda 10.2 \ cudann 8.1 \ tesla T4
- 版本号/Version：Paddle：2.3.2 gpu  PaddleOCR：2.6
- 问题描述：
参照[快速构建卡证类OCR](https://aistudio.baidu.com/aistudio/projectdetail/4459116?channelType=0&channel=0)成功在3060ti的机器上运行程序，把项目拷贝到Tesla T4机器上进行训练时，速度很慢，cpu一直100%，显存占用80%，但GPU利用率一直处于0，直到程序进行Eval时，GPU才会变成100%，之后又变成0，这是我的配置文件
```
Global:
  use_gpu: true
  use_xpu: false
  use_mlu: false
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./output/db_mv3/
  save_epoch_step: 10
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 50]
  cal_metric_during_train: False
  pretrained_model: ./pretrain_models/db_ren/best_accuracy
  checkpoints:  
  save_inference_dir: ./output/db_mv3/
  use_visualdl: True
  infer_img: /home/ysq/Public/IdCareRecognition/newPos
  save_res_path: ./output/det_db/predicts_db.txt
  label_list: /home/ysq/Public/PaddleOCR/myDetConfig/myLabels.txt
  num_classes: 9

Architecture:
  model_type: det
  algorithm: DB
  Transform:
  Backbone:
    name: ResNet_vd
    layers: 50
  Neck:
    name: DBFPN
    out_channels: 256
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/ysq/Public/PaddleOCR/train_data/det/
    label_file_list:
      - /home/ysq/Public/PaddleOCR/train_data/det/train.txt
    ratio_list: [1.0]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - IaaAugment:
          augmenter_args:
            - { 'type': Fliplr, 'args': { 'p': 0.5 } }
            - { 'type': Affine, 'args': { 'rotate': [-10, 10] } }
            - { 'type': Resize, 'args': { 'size': [0.5, 3] } }
      - EastRandomCropData:
          size: [960, 960]
          max_tries: 50
          keep_ratio: true
      - MakeBorderMap:
          shrink_ratio: 0.4
          thresh_min: 0.3
          thresh_max: 0.7
      - MakeShrinkMap:
          shrink_ratio: 0.4
          min_text_size: 8
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'threshold_map', 'threshold_mask', 'shrink_map', 'shrink_mask', 'class_mask'] # the order of the dataloader list
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 1
    num_workers: 2
    use_shared_memory: True

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/ysq/Public/PaddleOCR/train_data/det/
    label_file_list:
      - /home/ysq/Public/PaddleOCR/train_data/det/test.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - DetLabelEncode: # Class handling label
      - DetResizeForTest:
          resize_long: 960
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: ['image', 'shape', 'polys', 'ignore_tags']
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 1 # must be 1
    num_workers: 1
    use_shared_memory: True

```
期望：在Tesla T4上能快速训练
