### ISSUE TITLE
paddleOCR训练时调用GPU时没有报错，但是直接没有输出，cpu加速可以正常使用

### ISSUE THREAD

**Issue by Re-since** [PaddlePaddle/PaddleOCR#9016]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：win10
- 输入命令： 
> python tools/train.py -c ser_vi_layoutxlm_trained/ser_vi_layoutxlm_xfund_zh_udml.yml

![image](https://user-images.githubusercontent.com/92616158/217696781-2fd0cbfb-cdf4-49f9-ade5-8327485de754.png)

直接就退出了，没有模型输出，但是正常使用cpu可以
paddle-gpu也安装成功
![image](https://user-images.githubusercontent.com/92616158/217697032-be258657-06ce-497e-8167-eba87f879897.png)

配置文件：
```
Global:
  use_gpu: True
  epoch_num: &epoch_num 200
  log_smooth_window: 10
  print_batch_step: 10
  pretrained_model: ./ser_vi_layoutxlm_xfund_pretrained/best_accacy
  save_model_dir: ./ser_vi_layoutxlm_trained
  save_epoch_step: 2000
  # evaluation is run every 10 iterations after the 0th iteration
  eval_batch_step: [ 0, 19 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img: ./input/1.jpg
  save_res_path: ./output/ser_res
  pretrain_weights:
```
