### ISSUE TITLE
使用paddleocr关键信息抽取ser 通过训练模型去预测，效果还是可以的。但是只要我将模型导出成inference模型,效果就会差很多

### ISSUE THREAD

**Issue by ghghgha** [PaddlePaddle/PaddleOCR#9104]
**模型训练后测试**
`python tools/infer_kie_token_ser.py -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Architecture.Backbone.checkpoints=./output/ser_vi_layoutxlm_xfund_zh/best_accuracy Global.infer_img=./ppstructure/docs/kie/input/12121.png`
**模型导出成inference**
`python tools/export_model.py -c ./configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml -o Global.pretrained_model=./output/ser_vi_layoutxlm_xfund_zh/best_accuracy  Global.save_inference_dir=./inference/`
**模型导出成inference后测试**
`python kie/predict_kie_token_ser.py --kie_algorithm=LayoutXLM --ser_model_dir=../inference --image_dir=./docs/kie/input/12121.png --ser_dict_path=C:/Users/123/Desktop/OCR/data/data/class_list_ser_test1.txt --vis_font_path=../doc/fonts/simfang.ttf --ocr_order_method="tb-yx"`
**问题**：识别的文字所对应的标签，左边训练完后模型测试文字对应标签几乎都对，右边模型导出inference后预测文字标签全部乱了，检查了ser_dict_path都是同一文件，不知道哪里出问题了
![图片](https://user-images.githubusercontent.com/48711016/219289520-bd5c7a1b-73e2-417e-a280-cd5d7f1a13c1.png)

**其中：ser_vi_layoutxlm_xfund_zh.yml**
```
Global:
  use_gpu: True
  epoch_num: &epoch_num 50
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: ./output/ser_vi_layoutxlm_xfund_zh
  save_epoch_step: 2000
  eval_batch_step: [ 0, 19 ]
  cal_metric_during_train: False
  save_inference_dir:
  use_visualdl: False
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_42.jpg

  save_res_path: ./output/ser/xfund_zh/res
  kie_rec_model_dir: 
  kie_det_model_dir:

Architecture:
  model_type: kie
  algorithm: &algorithm "LayoutXLM"
  Transform:
  Backbone:
    name: LayoutXLMForSer
    pretrained: True
    checkpoints:
    # one of base or vi
    mode: vi
    num_classes: &num_classes 57

Loss:
  name: VQASerTokenLayoutLMLoss
  num_classes: *num_classes
  key: "backbone_out"

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Linear
    learning_rate: 0.00005
    epochs: *epoch_num
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 0.00000
    
PostProcess:
  name: VQASerTokenLayoutLMPostProcess
  class_path: &class_path C:/Users/123/Desktop/OCR/data/data/class_list_ser_test1.txt

Metric:
  name: VQASerTokenMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/123/Desktop/OCR/data/data/imgs
    label_file_list: 
      - C:/Users/123/Desktop/OCR/data/data/train_ser_test1.json
    ratio_list: [ 1.0 ]
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: False
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: &use_textline_bbox_info True
          # one of [None, "tb-yx"]
          order_method: &order_method "tb-yx"
      - VQATokenPad:
          max_seq_len: &max_seq_len 512
          return_attention_mask: True
      - VQASerTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 8
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/123/Desktop/OCR/data/data/imgs
    label_file_list:
      - C:/Users/123/Desktop/OCR/data/data/val_ser_test1.json
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          contains_re: False
          algorithm: *algorithm
          class_path: *class_path
          use_textline_bbox_info: *use_textline_bbox_info
          order_method: *order_method
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQASerTokenChunk:
          max_seq_len: *max_seq_len
      - Resize:
          size: [224,224]
      - NormalizeImage:
          scale: 1
          mean: [ 123.675, 116.28, 103.53 ]
          std: [ 58.395, 57.12, 57.375 ]
          order: 'hwc'
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'image', 'labels'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 8
    num_workers: 0
```
