### ISSUE TITLE
ser训练。报错

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9368]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
```
python3 tools/train.py -c configs/onezbill/zzszyfp_v1/ser_vi_layoutxlm.yml
```
- 完整报错/Complete Error Message：
```
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 180, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/tools/program.py", line 295, in train
    loss = loss_class(preds, batch)
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/DiskA/PycharmProjects/PaddleOCR-release-2.6/ppocr/losses/vqa_token_layoutlm_loss.py", line 38, in forward
    active_output = predicts.reshape(
  File "/usr/local/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 3543, in reshape
    out = _C_ops.reshape(x, shape)
ValueError: (InvalidArgument) The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 512, 89], X's size = 45568, 'shape' is [-1, 39], known capacity of 'shape' is -39.
  [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-45552 != -in_size:-45568.] (at /paddle/paddle/phi/infermeta/unary.cc:1417)


```
ser_vi_layoutxml.yml
```
Global:
  use_gpu: true
  epoch_num: 10
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/model/ser/output/ser_vi_layoutxlm/
  save_epoch_step: 2000
  eval_batch_step:
  - 0
  - 19
  cal_metric_during_train: false
  save_inference_dir: null
  use_visualdl: false
  seed: 2022
  infer_img: ppstructure/docs/kie/input/zh_val_42.jpg
  save_res_path: null
  kie_rec_model_dir: null
  kie_det_model_dir: null
Architecture:
  model_type: kie
  algorithm: LayoutXLM
  Transform: null
  Backbone:
    name: LayoutXLMForSer
    pretrained: true
    checkpoints: null
    mode: vi
    num_classes: 89
Loss:
  name: VQASerTokenLayoutLMLoss
  num_classes: 39
  key: backbone_out
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Linear
    learning_rate: 5.0e-05
    epochs: 5
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 0.0
PostProcess:
  name: VQASerTokenLayoutLMPostProcess
  class_path: /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/train_data/class_list.txt
Metric:
  name: VQASerTokenMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/train_data/zh_train/image
    label_file_list:
    - /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/train_data/zh_train/train.json
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - VQATokenLabelEncode:
        contains_re: false
        algorithm: LayoutXLM
        class_path: /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/train_data/class_list.txt
        use_textline_bbox_info: true
        order_method: tb-yx
    - VQATokenPad:
        max_seq_len: 512
        return_attention_mask: true
    - VQASerTokenChunk:
        max_seq_len: 512
    - Resize:
        size:
        - 224
        - 224
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - input_ids
        - bbox
        - attention_mask
        - token_type_ids
        - image
        - labels
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 1
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/train_data/zh_val/image
    label_file_list:
    - /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/train_data/zh_val/val.json
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - VQATokenLabelEncode:
        contains_re: false
        algorithm: LayoutXLM
        class_path: /home/DiskA/zncsPython/picture_ocr/zzszyfp_v1/train_data/class_list.txt
        use_textline_bbox_info: true
        order_method: tb-yx
    - VQATokenPad:
        max_seq_len: 512
        return_attention_mask: true
    - VQASerTokenChunk:
        max_seq_len: 512
    - Resize:
        size:
        - 224
        - 224
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - input_ids
        - bbox
        - attention_mask
        - token_type_ids
        - image
        - labels
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 4

```
