### ISSUE TITLE
My Trained Table Recognition Model does not work properly when used in layout_analysis. Works fine otherwise.

### ISSUE THREAD

**Issue by johntoma** [PaddlePaddle/PaddleOCR#9500]
Hello. When I use the table model I trained in the layout analysis process, it does not give proper results. All the detected cells are always on the top row for some reason. The model isn't being utilized properly when used in layout analysis, because if 

Here is an example (green boxes are cells)
![image](https://user-images.githubusercontent.com/83645945/226784125-9ddfbc66-c55a-463d-bcfa-b445674e717b.png)

But when I run it with this command, I get proper results:

> ```python table/predict_structure.py --table_model_dir=inference/my_table_model --table_char_dict_path=../ppocr/utils/dict/table_structure_dict_ch.txt --image_dir=docs/table/test/ --output=output/my_table_model```

#### I initialize table_engine like this:

![image](https://user-images.githubusercontent.com/83645945/226784383-59b4781a-ec29-41f5-8d3b-4e651d0a8eee.png)

#### And I predict like this:
![image](https://user-images.githubusercontent.com/83645945/226784452-04c7d442-9f8d-4a61-836b-07ae98638a8b.png)

I get no prediction errors when predicting, but the table recognition results are completely wrong. If I crop out the table img and run the above command, I get proper results. But for some reason when using ppstructure layout analysis, it gives me some strange results.

I've trained this model ontop of the `ch_ppstructure_mobile_v2.0_SLANet_infer` model, and I use the `table_structure_dict_ch.txt` as the dict.

Any idea what might be causing this? Is there some parameter I need to add in my `ppstructure_args` that will make the model work properly?

### Edit: Here is my training config (in case it's needed)
```
Global:
  use_gpu: True
  epoch_num: 60
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/SLANet_ch
  save_epoch_step: 60
  # evaluation is run every 331 iterations after the 0th iteration
  eval_batch_step: [0, 780]
  cal_metric_during_train: True
  pretrained_model: models/ch_ppstructure_mobile_v2.0_SLANet_train/best_accuracy
  checkpoints: 
  save_inference_dir: ./output/SLANet_ch/infer
  use_visualdl: False
  infer_img: ppstructure/docs/table/table.jpg
  # for data or label process
  character_dict_path: ppocr/utils/dict/table_structure_dict_ch.txt
  character_type: en
  max_text_length: &max_text_length 500
  box_format: &box_format xyxyxyxy # 'xywh', 'xyxy', 'xyxyxyxy'
  infer_mode: False
  use_sync_bn: True
  save_res_path: output/infer

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  lr:
    learning_rate: 0.00005
  regularizer:
    name: 'L2'
    factor: 0.00000

Architecture:
  model_type: table
  algorithm: SLANet
  Backbone:
    name: PPLCNet
    scale: 1.0
    pretrained: True
    use_ssld: True
  Neck:
    name: CSPPAN
    out_channels: 96
  Head:
    name: SLAHead
    hidden_size: 256
    max_text_length: *max_text_length
    loc_reg_num: &loc_reg_num 8

Loss:
  name: SLALoss
  structure_weight: 1.0
  loc_weight: 2.0
  loc_loss: smooth_l1

PostProcess:
  name: TableLabelDecode
  merge_no_span_structure: &merge_no_span_structure True

Metric:
  name: TableMetric
  main_indicator: acc
  compute_bbox_metric: False
  loc_reg_num: *loc_reg_num
  box_format: *box_format
  del_thead_tbody: True

Train:
  dataset:
    name: PubTabDataSet
    data_dir: train_data/table/train/
    label_file_list: [train_data/table/train/train.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: True
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'structure', 'bboxes', 'bbox_masks', 'shape' ]
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: PubTabDataSet
    data_dir: train_data/table/val/
    label_file_list: [train_data/table/val/val.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: True
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'structure', 'bboxes', 'bbox_masks', 'shape' ]
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 1

```
