### ISSUE TITLE
ser预测，通过动态预测正常。但是转为inference预测之后。会有多个。是什么原因呢？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9667]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components：
paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
```
# ser通过inference预测
cd ppstructure/kie/
python3 predict_kie_token_ser.py \
--kie_algorithm=LayoutXLM \
--ser_model_dir=/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/ser/inference/ser_vi_layoutxlm_inference \
--image_dir=/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/uie_imgs/1-3.jpg \
--ser_dict_path=/home/DiskA/zncsPython/picture_ocr/xsd_v1/train_data/class_list.txt \
--vis_font_path=../doc/fonts/simfang.ttf \
--ocr_order_method="tb-yx" \
--output=/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/uie_imgsresult/ \
--det_limit_side_len=736 \
--det_limit_type="min" \
--rec_model_dir=/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/rec/inference/ch_PP-OCRv3_rec_infer \
--det_model_dir=/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/det/inference/det_db_dml_inference


# ser通过动态度预测
python3 tools/infer_kie_token_ser.py -c configs/onezbill/xsd_v1/ser_vi_layoutxlm_inference.yml  -o \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/xsd_v1/test/uie_imgs/1-3.jpg \
Global.infer_mode=True \
Global.kie_rec_model_dir=/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/rec/inference/ch_PP-OCRv3_rec_infer \
Global.kie_det_model_dir=/home/DiskA/zncsPython/picture_ocr/xsd_v1/model/det/inference/det_db_dml_inference/Student
```
- 完整报错/Complete Error Message：
是什么原因呢？对了前后 参数这几个好像一样。还有哪些参数吗
```
   algorithm: LayoutXLM，
  class_path: /home/DiskA/zncsPython/picture_ocr/xsd_v1/train_data/class_list.txt
  use_textline_bbox_info: true
  order_method: tb-yx
```
动态预测正常。结果如图
![image](https://user-images.githubusercontent.com/32863094/230422517-98f0ded0-4c31-478e-9271-dc6b26d63bd4.png)

inference预测。结果多个。如下图
![image](https://user-images.githubusercontent.com/32863094/230422477-1798bd16-1530-472a-9ce6-ea0811587d80.png)

**Comment by rexzhengzhihong** [comment]
interfence处理参数和配置文件训练参数。看着都一样
```
pre_process_list = [{
            'VQATokenLabelEncode': {
                'algorithm': args.kie_algorithm,
                'class_path': args.ser_dict_path,
                'contains_re': False,
                'ocr_engine': self.ocr_engine,
                'order_method': args.ocr_order_method,
            }
        }, {
            'VQATokenPad': {
                'max_seq_len': 512,
                'return_attention_mask': True
            }
        }, {
            'VQASerTokenChunk': {
                'max_seq_len': 512,
                'return_attention_mask': True
            }
        }, {
            'Resize': {
                'size': [224, 224]
            }
        }, {
            'NormalizeImage': {
                'std': [58.395, 57.12, 57.375],
                'mean': [123.675, 116.28, 103.53],
                'scale': '1',
                'order': 'hwc'
            }
        }, {
            'ToCHWImage': None
        }, {
            'KeepKeys': {
                'keep_keys': [
                    'input_ids', 'bbox', 'attention_mask', 'token_type_ids',
                    'image', 'labels', 'segment_offset_id', 'ocr_info',
                    'entities'
                ]
            }
        }]
        postprocess_params = {
            'name': 'VQASerTokenLayoutLMPostProcess',
            "class_path": args.ser_dict_path,
        }
```

```
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/DiskA/zncsPython/picture_ocr/xsd_v1/train_data/zh_val/image
    label_file_list:
    - /home/DiskA/zncsPython/picture_ocr/xsd_v1/train_data/zh_val/val.json
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - VQATokenLabelEncode:
        contains_re: false
        algorithm: LayoutXLM
        class_path: /home/DiskA/zncsPython/picture_ocr/xsd_v1/train_data/class_list.txt
        use_textline_bbox_info: true
        order_method: tb-yx
    - VQATokenPad:
        max_seq_len: 512
        return_attention_mask: true
    - VQASerTokenChunk:
        max_seq_len: 512
    - Resize:
        size:
        - 224
        - 224
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - input_ids
        - bbox
        - attention_mask
        - token_type_ids
        - image
        - labels
```
