### ISSUE TITLE
自己训练的表格模型。预测结果很神奇。预测一次就有不一样的效果。是设么原因呢？

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleOCR#9816]
请提供下述完整信息以便快速定位问题/Please provide the following information to quickly locate the problem

- 系统环境/System Environment：
ubuntu20.04
- 版本号/Version：Paddle：  PaddleOCR： 问题相关组件/Related components： paddle 1.0.2
paddle-bfloat 0.1.2
paddle2onnx 0.9.7
paddlefsl 1.1.0
paddlenlp 2.4.1
paddleocr 2.6.1.2
paddlepaddle-gpu 2.4.1.post116
pandas 1.1.5
pandocfilters 1.5.0
- 运行指令/Command Code：
```
# 预测表格图像(使用训练模型)
python3 tools/infer_table.py \
-c configs/table/SLANet.yml \
-o Global.pretrained_model=/home/DiskA/zncsPython/picture_ocr/table/model/output/SLANet_finetune/best_accuracy \
Global.infer_img=/home/DiskA/zncsPython/picture_ocr/table/test/table_predict/3_table.jpg \
Global.save_res_path=/home/DiskA/zncsPython/picture_ocr/table/test/table_predict_output
```
- 完整报错/Complete Error Message：
预测命令运行第一次。空的
![image](https://user-images.githubusercontent.com/32863094/234164892-6db51bec-755f-4f95-bc58-cf9ad187add6.png)
预测命令运行第二次。有一些结果
![image](https://user-images.githubusercontent.com/32863094/234164801-11767105-efec-4fbd-a869-36524687d669.png)
预测命令运行第三次。空的
预测命令运行第三次，又是不同的结果
![image](https://user-images.githubusercontent.com/32863094/234165327-39e3923c-f136-44ea-a1a1-267da830610d.png)

- SLANet.yml
```
Global:
  use_gpu: True
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: /home/DiskA/zncsPython/picture_ocr/table/model/output/SLANet_finetune/
  save_epoch_step: 20
  # evaluation is run every 331 iterations after the 0th iteration
  eval_batch_step: [0, 20]
  cal_metric_during_train: True
  pretrained_model: ./pretrain_models/ch_ppstructure_mobile_v2.0_SLANet_train/best_accuracy.pdparams
  checkpoints: 
  save_inference_dir: ./output/SLANet_ch/infer
  use_visualdl: False
  infer_img: ppstructure/docs/table/table.jpg
  # for data or label process
  character_dict_path: ppocr/utils/dict/table_structure_dict_ch.txt
  character_type: en
  max_text_length: &max_text_length 500
  box_format: &box_format xyxyxyxy # 'xywh', 'xyxy', 'xyxyxyxy'
  infer_mode: False
  use_sync_bn: True
  save_res_path: output/infer

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  lr:
    learning_rate: 0.0005
    name: Cosine
    warmup_epoch: 0
  regularizer:
    name: 'L2'
    factor: 0.00000

Architecture:
  model_type: table
  algorithm: SLANet
  Backbone:
    name: PPLCNet
    scale: 1.0
    pretrained: True
    use_ssld: True
  Neck:
    name: CSPPAN
    out_channels: 96
  Head:
    name: SLAHead
    hidden_size: 256
    max_text_length: *max_text_length
    loc_reg_num: &loc_reg_num 8

Loss:
  name: SLALoss
  structure_weight: 1.0
  loc_weight: 2.0
  loc_loss: smooth_l1

PostProcess:
  name: TableLabelDecode
  merge_no_span_structure: &merge_no_span_structure True

Metric:
  name: TableMetric
  main_indicator: acc
  compute_bbox_metric: False
  loc_reg_num: *loc_reg_num
  box_format: *box_format
  del_thead_tbody: True

Train:
  dataset:
    name: PubTabDataSet
    data_dir: /home/DiskA/zncsPython/picture_ocr/table/paddleLable_tagging_data/
    label_file_list: ['/home/DiskA/zncsPython/picture_ocr/table/paddleLable_tagging_data/train.txt']
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'structure', 'bboxes', 'bbox_masks', 'shape' ]
  loader:
    shuffle: True
    batch_size_per_card: 2
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: PubTabDataSet
    data_dir: /home/DiskA/zncsPython/picture_ocr/table/paddleLable_tagging_data/
    label_file_list: [/home/DiskA/zncsPython/picture_ocr/table/paddleLable_tagging_data/val.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'structure', 'bboxes', 'bbox_masks', 'shape' ]
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 2
    num_workers: 1


```
