### ISSUE TITLE
Terrible result about table reco 

### ISSUE THREAD

**Issue by github2016-yuan** [PaddlePaddle/PaddleOCR#9872]
I get bad result about table reco and ocr. Here are some details.

About system: win10 /pycharm/cuda11.2/ paddleocr 2.6.1.1 
(1) I get train data [Get Tabel Data](https://github.com/WenmuZhou/TableGeneration)
(2) Split the dataset with 90% for training (18k images) and 10% for testing(2k images)
(3)Use SLANet for training and the config file is my_SLANet_ch.yml:
```
my_SLANet_ch.yml
Global:
  use_gpu: True
  epoch_num: 7 #400
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/SLANet_ch
  save_epoch_step: 400
  # evaluation is run every 331 iterations after the 0th iteration
  eval_batch_step: [0, 331]
  cal_metric_during_train: True
  pretrained_model: .././pretrain_models/ch_ppstructure_mobile_v2.0_SLANet_train/best_accuracy.pdparams
  checkpoints: 
  save_inference_dir: ./output/SLANet_ch/infer
  use_visualdl: False
  infer_img: ppstructure/docs/table/table.jpg
  # for data or label process
  character_dict_path: /ppocr/utils/dict/table_structure_dict_ch.txt
  character_type: en
  max_text_length: &max_text_length 500
  box_format: &box_format xyxyxyxy # 'xywh', 'xyxy', 'xyxyxyxy'
  infer_mode: False
  use_sync_bn: True
  save_res_path: output/infer

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  clip_norm: 5.0
  lr:
    learning_rate: 0.0005 #0.001
  regularizer:
    name: 'L2'
    factor: 0.00000

Architecture:
  model_type: table
  algorithm: SLANet
  Backbone:
    name: PPLCNet
    scale: 1.0
    pretrained: True
    use_ssld: True
  Neck:
    name: CSPPAN
    out_channels: 96
  Head:
    name: SLAHead
    hidden_size: 256
    max_text_length: *max_text_length
    loc_reg_num: &loc_reg_num 8

Loss:
  name: SLALoss
  structure_weight: 1.0
  loc_weight: 2.0
  loc_loss: smooth_l1

PostProcess:
  name: TableLabelDecode
  merge_no_span_structure: &merge_no_span_structure True

Metric:
  name: TableMetric
  main_indicator: acc
  compute_bbox_metric: False
  loc_reg_num: *loc_reg_num
  box_format: *box_format
  del_thead_tbody: True

Train:
  dataset:
    name: PubTabDataSet
    data_dir: E:/XYDataSets                               #train_data/table/train/
    label_file_list: [E:/XYDataSets/table_gen_dataset/train.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'structure', 'bboxes', 'bbox_masks', 'shape' ]
  loader:
    shuffle: True
    batch_size_per_card: 8 #
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: PubTabDataSet
    data_dir: E:/XYDataSets
    label_file_list: [E:/XYDataSets/table_gen_dataset/val.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - TableLabelEncode:
          learn_empty_box: False
          merge_no_span_structure: *merge_no_span_structure
          replace_empty_cell_token: False
          loc_reg_num: *loc_reg_num
          max_text_length: *max_text_length
      - TableBoxEncode:
          in_box_format: *box_format
          out_box_format: *box_format
      - ResizeTableImage:
          max_len: 488
      - NormalizeImage:
          scale: 1./255.
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          order: 'hwc'
      - PaddingTableImage:
          size: [488, 488]
      - ToCHWImage:
      - KeepKeys:
          keep_keys: [ 'image', 'structure', 'bboxes', 'bbox_masks', 'shape' ]
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 8 #48
    num_workers: 1

```
(4) Train with the cmd:
python3 tools/train.py -c ../../my_SLANet_ch.yml

I use only 7 epoches and get nice acc.
```
...
[2023/04/27 15:18:47] ppocr INFO: epoch: [7/7], global_step: 15680, lr: 0.000500, acc: 0.875000, loss: 0.001527, structure_loss: 0.000573, loc_loss: 0.000923, avg_reader_cost: 0.00185 s, avg_batch_cost: 1.09576 s, avg_samples: 8.0, ips: 7.30084 samples/s, eta: 0:01:01
[2023/04/27 15:19:07] ppocr INFO: epoch: [7/7], global_step: 15700, lr: 0.000500, acc: 0.750000, loss: 0.006370, structure_loss: 0.002611, loc_loss: 0.003888, avg_reader_cost: 0.00128 s, avg_batch_cost: 1.02084 s, avg_samples: 8.0, ips: 7.83666 samples/s, eta: 0:00:39
[2023/04/27 15:19:27] ppocr INFO: epoch: [7/7], global_step: 15720, lr: 0.000500, acc: 0.875000, loss: 0.002966, structure_loss: 0.000900, loc_loss: 0.001946, avg_reader_cost: 0.00110 s, avg_batch_cost: 0.97772 s, avg_samples: 8.0, ips: 8.18230 samples/s, eta: 0:00:18
[2023/04/27 15:19:43] ppocr INFO: save model in ./output/SLANet_ch\latest
[2023/04/27 15:19:43] ppocr INFO: best metric, acc: 0.9613453810435013, is_float16: False, fps: 19.589961838717645, best_epoch: 7

```

I also eval the model and the result is still good.

(5)Last combine PP-OCRv3 and SLANet for table reco and text reco. 
ch_PP-OCRv3_det_slim_infer、ch_PP-OCRv3_rec_slim_infer

! python3 table/predict_table.py \
    --det_model_dir=inference/ch_PP-OCRv3_det_slim_infer \
    --rec_model_dir=inference/ch_PP-OCRv3_rec_slim_infer  \
    --table_model_dir=/home/aistudio/SLANet_ch/infer \
    --rec_char_dict_path=../ppocr/utils/ppocr_keys_v1.txt \
    --table_char_dict_path=../ppocr/utils/dict/table_structure_dict.txt \
    --image_dir=/home/aistudio/data/data165849/table_gen_dataset/img/no_border_18298_G7XZH93DDCMATGJQ8RW2.jpg \
    --output=../output/table

No err but the result is very bad， it almost has no effect.
